/**
 * Dữ liệu giả lập dùng chung: Yêu cầu cung cấp thông tin và Yêu cầu cung cấp bản sao (Website Quản trị - Module Biện pháp bảo đảm).
 * Dùng cho màn Kiểm tra và xử lý hồ sơ (kiem_tra_ho_so.html) và màn Tra cứu hồ sơ (tra_cuu_thong_tin.html).
 */
const ccttOfficerRequests = [
    {
        id: 'CCTT-20260801-000201',
        registeredAt: '01/08/2026 09:15',
        customerId: 'KH-HUNG-02',
        requester: 'Ông Nguyễn Văn Hùng',
        address: 'Số 12 phố Duy Tân, phường Dịch Vọng Hậu, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Số đăng ký',
        inputData: '1505170802',
        status: 'Chờ duyệt',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: false
    },
    {
        id: 'CCTT-20260801-000202',
        registeredAt: '01/08/2026 10:40',
        customerId: 'KH-MINHTAM-01',
        requester: 'Công ty Cổ phần Đầu tư Minh Tâm',
        address: 'Tầng 6, tòa nhà FPT, Cầu Giấy, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Bên bảo đảm',
        inputData: 'Công dân Việt Nam - CCCD 091000000004',
        status: 'Chờ duyệt',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'noData',
        signedDraft: false
    },
    {
        id: 'CCTT-20260731-000177',
        registeredAt: '31/07/2026 15:05',
        customerId: 'KH-FPT-07',
        requester: 'Ngân hàng TMCP FPT',
        address: 'Tòa nhà FPT, Cầu Giấy, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Số khung',
        inputData: 'RLZ2026KHUNG0007VN',
        status: 'Chờ duyệt',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true
    },
    {
        id: 'CCTT-20260730-000171',
        registeredAt: '30/07/2026 11:25',
        customerId: 'KH-ANPHU-05',
        requester: 'Công ty TNHH An Phú',
        address: 'Số 88 Lê Văn Lương, Thanh Xuân, Hà Nội',
        source: 'Cán bộ nhập liệu',
        criteria: 'Số đăng ký',
        inputData: '1505170868',
        status: 'Bị trả lại',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true,
        returnReason: 'Lãnh đạo yêu cầu rà soát lại tiêu chí tra cứu theo hồ sơ giấy, thông tin giấy tờ tùy thân chưa khớp với bản gốc.',
        returnedBy: 'Lê Hoàng Long - Giám đốc Trung tâm',
        returnedAt: '30/07/2026 14:15',
        returnHistory: [
            { reason: 'Lãnh đạo yêu cầu rà soát lại tiêu chí tra cứu theo hồ sơ giấy, thông tin giấy tờ tùy thân chưa khớp với bản gốc.', by: 'Lê Hoàng Long - Giám đốc Trung tâm', at: '30/07/2026 14:15', resubmittedAt: '' }
        ]
    },
    {
        id: 'CCTT-20260731-000178',
        registeredAt: '31/07/2026 16:30',
        customerId: 'KH-NAMHAI-08',
        requester: 'Công ty Cổ phần Thương mại Nam Hải',
        address: 'Số 108 Lò Đúc, phường Đống Mác, quận Hai Bà Trưng, Hà Nội',
        source: 'Cán bộ nhập liệu',
        criteria: 'Bên bảo đảm',
        inputData: 'Mã số thuế: 0108899889',
        status: 'Bị trả lại',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true,
        returnReason: 'Thông tin kết quả tra cứu chưa đầy đủ theo danh mục tài sản bên bảo đảm khai báo.',
        returnedBy: 'Trần Thị Minh Nguyệt - Phó Giám đốc Trung tâm',
        returnedAt: '31/07/2026 16:30',
        returnHistory: [
            { reason: 'Thông tin kết quả tra cứu chưa đầy đủ theo danh mục tài sản bên bảo đảm khai báo.', by: 'Trần Thị Minh Nguyệt - Phó Giám đốc Trung tâm', at: '31/07/2026 16:30', resubmittedAt: '' },
            { reason: 'Văn bản dự thảo thiếu chữ ký số của Cán bộ lập biểu.', by: 'Lê Hoàng Long - Giám đốc Trung tâm', at: '31/07/2026 09:20', resubmittedAt: '31/07/2026 11:00' }
        ]
    },
    {
        id: 'CCTT-20260729-000165',
        registeredAt: '29/07/2026 08:40',
        customerId: 'KH-LANANH-03',
        requester: 'Bà Trần Lan Anh',
        address: 'Số 45 Nguyễn Chí Thanh, Đống Đa, Hà Nội',
        source: 'Cán bộ nhập liệu',
        criteria: 'Số đăng ký',
        inputData: '1505170855',
        status: 'Duyệt chờ ký',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'noData',
        signedDraft: true
    },
    {
        id: 'CCTT-20260728-000158',
        registeredAt: '28/07/2026 16:20',
        customerId: 'KH-HTC-04',
        requester: 'Công ty Cổ phần Xây dựng và Phát triển HTC',
        address: 'Đường số 5, cụm công nghiệp Tứ Hạ mở rộng, thành phố Huế',
        source: 'Website khách hàng',
        criteria: 'Số đăng ký',
        inputData: '1505170802',
        status: 'Hoàn thành',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true
    },
    {
        id: 'CCTT-20260727-000149',
        registeredAt: '27/07/2026 09:10',
        customerId: 'KH-MINHHUNG-09',
        requester: 'Ông Lê Minh Hùng',
        address: 'Số 9 Nguyễn Trãi, Hà Đông, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Bên bảo đảm',
        inputData: 'CCCD 091000000099',
        status: 'Bị từ chối',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'noData',
        signedDraft: false,
        rejectReason: 'Thông tin hồ sơ yêu cầu tra cứu không tồn tại trên hệ thống dữ liệu quốc gia.',
        rejectedBy: 'Nguyễn Văn Cán Bộ',
        rejectedAt: '27/07/2026 10:30',
        rejectLeader: 'Lê Hoàng Long - Giám đốc Trung tâm',
        rejectDraftFile: 'Van_ban_tu_choi_CCTT_20260727_000149_Signed.pdf',
        rejectFile: 'Bien_ban_kiem_tra_khong_hop_le_099.pdf'
    },
    {
        id: 'CCTT-20260802-000210',
        registeredAt: '02/08/2026 09:30',
        customerId: 'KH-NAMLONG-01',
        requester: 'Công ty TNHH Đầu tư Nam Long',
        address: 'Số 15 Lê Văn Thiêm, Thanh Xuân, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Số đăng ký',
        inputData: '1505170802',
        status: 'Chờ ký',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true
    },
    {
        id: 'CCTT-20260802-000211',
        registeredAt: '02/08/2026 10:15',
        customerId: 'KH-VIB-02',
        requester: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)',
        address: 'Tòa nhà VIB, 111 Pasteur, Q.1, TP.HCM',
        source: 'Dịch vụ công Quốc gia',
        criteria: 'Bên bảo đảm',
        inputData: 'Công ty CP Tập đoàn Đất Xanh',
        status: 'Chờ ký',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true
    },
    {
        id: 'CCTT-20260802-000212',
        registeredAt: '02/08/2026 14:00',
        customerId: 'KH-THUHANG-03',
        requester: 'Bà Đỗ Thu Hằng',
        address: 'Số 88 Cầu Giấy, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Số khung',
        inputData: 'VNFPT2026CHOKY001',
        status: 'Chờ ký',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'noData',
        signedDraft: false
    },
    {
        id: 'CCTT-20260803-000220',
        registeredAt: '03/08/2026 08:30',
        customerId: 'KH-VCB-01',
        requester: 'Ngân hàng TMCP Ngoại thương VN (Vietcombank)',
        address: '198 Trần Quang Khải, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Số đăng ký',
        inputData: '1505156438',
        status: 'Hoàn thành',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true
    },
    {
        id: 'CCTT-20260803-000221',
        registeredAt: '03/08/2026 11:10',
        customerId: 'KH-NAMTV-05',
        requester: 'Ông Trần Văn Nam',
        address: 'Số 12 Kim Mã, Ba Đình, Hà Nội',
        source: 'Dịch vụ công Quốc gia',
        criteria: 'Bên bảo đảm',
        inputData: 'Công ty CP Sao Mai',
        status: 'Hoàn thành',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'hasData',
        signedDraft: true
    },
    {
        id: 'CCTT-20260804-000230',
        registeredAt: '04/08/2026 15:00',
        customerId: 'KH-TUANHM-08',
        requester: 'Ông Hoàng Minh Tuấn',
        address: 'Số 50 Giải Phóng, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Số đăng ký',
        inputData: '9999999999',
        status: 'Bị từ chối',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'noData',
        signedDraft: false,
        rejectReason: 'Thông tin hồ sơ yêu cầu tra cứu không tồn tại trên hệ thống và không đúng thẩm quyền xử lý.',
        rejectedBy: 'Trần Thị Thu Trang - Cán bộ tiếp nhận',
        rejectedAt: '04/08/2026 15:40',
        rejectLeader: 'Lê Hoàng Long - Giám đốc Trung tâm',
        rejectDraftFile: 'Van_ban_tu_choi_CCTT_20260804_000230_Signed.pdf',
        rejectFile: 'Phieu_kiem_tra_tham_quyen.pdf'
    },
    {
        id: 'CCTT-20260804-000231',
        registeredAt: '04/08/2026 16:20',
        customerId: 'KH-BACNAM-09',
        requester: 'Công ty TNHH Vận tải Bắc Nam',
        address: 'Số 200 Giải Phóng, Phương Liệt, Thanh Xuân, Hà Nội',
        source: 'Website khách hàng',
        criteria: 'Số khung',
        inputData: 'INVALIDKHUNG888',
        status: 'Bị từ chối',
        officer: 'Nguyễn Văn Cán Bộ',
        resultType: 'noData',
        signedDraft: false,
        rejectReason: 'Số khung phương tiện không đúng định dạng chuẩn theo cơ sở dữ liệu đăng kiểm.',
        rejectedBy: 'Nguyễn Văn Cán Bộ',
        rejectedAt: '04/08/2026 17:00',
        rejectLeader: 'Lê Hoàng Long - Giám đốc Trung tâm',
        rejectDraftFile: 'Van_ban_tu_choi_CCTT_20260804_000231_Signed.pdf',
        rejectFile: 'Chung_thu_giam_dinh_so_khung.pdf'
    }
];

const officerCopyRequests = [
    {
        id: 'BS-2026-000001',
        paperNo: 'PG-2026-001',
        registeredAt: '23/09/2026 08:40',
        customerId: 'KH-ONLINE-09882',
        requester: 'Ngân hàng TMCP Ngoại thương Việt Nam - Chi nhánh Sở giao dịch',
        address: 'Số 11 Láng Hạ, phường Thành Công, quận Ba Đình, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '23/09/2026 08:50',
        draftFile: ''
    },
    {
        id: 'BS-2026-000002',
        paperNo: 'PG-2026-002',
        registeredAt: '23/09/2026 09:05',
        customerId: 'KH-ANVIET-09',
        requester: 'Công ty Luật TNHH An Việt',
        address: 'Số 45 phố Nguyễn Thị Định, phường Trung Hòa, quận Cầu Giấy, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao kèm thông báo về việc đăng ký thế chấp',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '23/09/2026 09:12',
        draftFile: ''
    },
    {
        id: 'BS-2026-000003',
        paperNo: 'PG-2026-003',
        registeredAt: '23/09/2026 09:20',
        customerId: 'KH-HOANG-07',
        requester: 'Ông Lê Đức Hoàng',
        address: 'Số 8 Nguyễn Trãi, phường Thanh Xuân Trung, quận Thanh Xuân, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 0,
        feeStatus: 'Miễn phí',
        status: 'Bị trả lại',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '23/09/2026 09:25',
        draftFile: '',
        returnReason: 'Lãnh đạo yêu cầu rà soát lại Số đăng ký hồ sơ gốc, Số đăng ký trên phiếu tiếp nhận chưa khớp với nội dung đơn giấy.',
        returnedBy: 'Lê Hoàng Long - Giám đốc Trung tâm',
        returnedAt: '23/09/2026 10:15',
        returnHistory: [
            { reason: 'Lãnh đạo yêu cầu rà soát lại Số đăng ký hồ sơ gốc, Số đăng ký trên phiếu tiếp nhận chưa khớp với nội dung đơn giấy.', by: 'Lê Hoàng Long - Giám đốc Trung tâm', at: '23/09/2026 10:15', resubmittedAt: '' }
        ]
    },
    {
        id: 'BS-2026-000004',
        paperNo: 'PG-2026-004',
        registeredAt: '23/09/2026 09:45',
        customerId: 'KH-BIDV-01',
        requester: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam - Chi nhánh Hà Thành',
        address: 'Số 74 phố Thợ Nhuộm, phường Trần Hưng Đạo, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '03 bản',
        quantity: 3,
        fee: 90000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '23/09/2026 09:55',
        draftFile: ''
    },
    {
        id: 'BS-2026-000005',
        paperNo: 'PG-2026-005',
        registeredAt: '23/09/2026 10:15',
        customerId: 'KH-TCB-02',
        requester: 'Ngân hàng TMCP Kỹ thương Việt Nam - Khối KHDN',
        address: 'Số 191 Bà Triệu, phường Lê Đại Hành, quận Hai Bà Trưng, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '23/09/2026 10:20',
        draftFile: ''
    },
    {
        id: 'BS-2026-000006',
        paperNo: 'PG-2026-006',
        registeredAt: '23/09/2026 10:50',
        customerId: 'KH-VPB-03',
        requester: 'Ngân hàng TMCP Việt Nam Thịnh Vượng - Trung tâm Xử lý nợ',
        address: 'Số 89 Láng Hạ, phường Láng Hạ, quận Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao kèm thông báo về việc đăng ký thế chấp',
        copyType: 'Bản sao giấy',
        copyQty: '01 bản',
        quantity: 1,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '23/09/2026 11:00',
        draftFile: ''
    },
    {
        id: 'BS-2026-000007',
        paperNo: 'PG-2026-007',
        registeredAt: '23/09/2026 11:15',
        customerId: 'KH-MB-04',
        requester: 'Ngân hàng TMCP Quân đội - Chi nhánh Ba Đình',
        address: 'Số 28 Điện Biên Phủ, phường Điện Biên, quận Ba Đình, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '23/09/2026 11:22',
        draftFile: ''
    },
    {
        id: 'BS-2026-000008',
        paperNo: 'PG-2026-008',
        registeredAt: '22/09/2026 08:30',
        customerId: 'KH-SHB-05',
        requester: 'Ngân hàng TMCP Sài Gòn - Hà Nội - PGD Tràng An',
        address: 'Số 77 Trần Hưng Đạo, phường Hàng Bông, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 08:40',
        draftFile: ''
    },
    {
        id: 'BS-2026-000009',
        paperNo: 'PG-2026-009',
        registeredAt: '22/09/2026 09:10',
        customerId: 'KH-ACB-06',
        requester: 'Ngân hàng TMCP Á Châu - Chi nhánh Hà Nội',
        address: 'Số 184 Bà Triệu, phường Nguyễn Du, quận Hai Bà Trưng, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 09:20',
        draftFile: ''
    },
    {
        id: 'BS-2026-000010',
        paperNo: 'PG-2026-010',
        registeredAt: '22/09/2026 10:00',
        customerId: 'KH-HDB-07',
        requester: 'Ngân hàng TMCP Phát triển TP.HCM - Chi nhánh Hoàn Kiếm',
        address: 'Số 32 phố Hai Bà Trưng, phường Tràng Tiền, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Bị trả lại',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 10:10',
        draftFile: '',
        returnReason: 'Dữ liệu người yêu cầu trên đơn giấy chưa đồng nhất với CSDL đăng ký biện pháp bảo đảm.',
        returnedBy: 'Trần Thị Minh Nguyệt - Phó Giám đốc Trung tâm',
        returnedAt: '22/09/2026 11:30',
        returnHistory: [
            { reason: 'Dữ liệu người yêu cầu trên đơn giấy chưa đồng nhất với CSDL đăng ký biện pháp bảo đảm.', by: 'Trần Thị Minh Nguyệt - Phó Giám đốc Trung tâm', at: '22/09/2026 11:30', resubmittedAt: '' }
        ]
    },
    {
        id: 'BS-2026-000011',
        paperNo: 'PG-2026-011',
        registeredAt: '22/09/2026 10:45',
        customerId: 'KH-VIB-08',
        requester: 'Ngân hàng TMCP Quốc tế Việt Nam - PGD Cầu Giấy',
        address: 'Tòa nhà Detech, số 8C Tôn Thất Thuyết, Mỹ Đình 2, Nam Từ Liêm, Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '04 bản',
        quantity: 4,
        fee: 120000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 11:00',
        draftFile: ''
    },
    {
        id: 'BS-2026-000012',
        paperNo: 'PG-2026-012',
        registeredAt: '22/09/2026 14:15',
        customerId: 'KH-TPB-09',
        requester: 'Ngân hàng TMCP Tiên Phong - Trung tâm Kinh doanh Hội sở',
        address: 'Số 57 phố Lý Thường Kiệt, phường Trần Hưng Đạo, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 14:25',
        draftFile: ''
    },
    {
        id: 'BS-2026-000013',
        paperNo: 'PG-2026-013',
        registeredAt: '22/09/2026 15:00',
        customerId: 'KH-MSB-10',
        requester: 'Ngân hàng TMCP Hàng Hải Việt Nam - Chi nhánh Đống Đa',
        address: 'Số 54A Nguyễn Chí Thanh, phường Láng Thượng, quận Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 15:10',
        draftFile: ''
    },
    {
        id: 'BS-2026-000014',
        paperNo: 'PG-2026-014',
        registeredAt: '22/09/2026 15:40',
        customerId: 'KH-LPB-11',
        requester: 'Ngân hàng TMCP Lộc Phát Việt Nam - Chi nhánh Hà Nội',
        address: 'Tòa nhà Thaiholdings, 210 Trần Quang Khải, Tràng Tiền, Hoàn Kiếm, Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 15:50',
        draftFile: ''
    },
    {
        id: 'BS-2026-000015',
        paperNo: 'PG-2026-015',
        registeredAt: '22/09/2026 16:20',
        customerId: 'KH-SEAB-12',
        requester: 'Ngân hàng TMCP Đông Nam Á - Chi nhánh Thăng Long',
        address: 'Số 25 phố Trần Hưng Đạo, phường Phan Chu Trinh, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao kèm thông báo về việc đăng ký thế chấp',
        copyType: 'Bản sao giấy',
        copyQty: '01 bản',
        quantity: 1,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 16:30',
        draftFile: ''
    },
    {
        id: 'BS-2026-000016',
        paperNo: 'PG-2026-016',
        registeredAt: '21/09/2026 08:45',
        customerId: 'KH-OJB-13',
        requester: 'Ngân hàng Thương mại TNHH MTV Đại Dương',
        address: 'Số 18 đường Láng Hạ, phường Thành Công, quận Ba Đình, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '21/09/2026 08:55',
        draftFile: ''
    },
    {
        id: 'BS-2026-000017',
        paperNo: 'PG-2026-017',
        registeredAt: '21/09/2026 09:30',
        customerId: 'KH-GPB-14',
        requester: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu',
        address: 'Số 109 phố Trần Hưng Đạo, phường Cửa Nam, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '21/09/2026 09:40',
        draftFile: ''
    },
    {
        id: 'BS-2026-000018',
        paperNo: 'PG-2026-018',
        registeredAt: '21/09/2026 10:15',
        customerId: 'KH-CB-15',
        requester: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',
        address: 'Tòa nhà Capital Tower, 109 Trần Hưng Đạo, Cửa Nam, Hoàn Kiếm, Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 0,
        feeStatus: 'Miễn phí',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '21/09/2026 10:20',
        draftFile: ''
    },
    {
        id: 'BS-2026-000019',
        paperNo: 'PG-2026-019',
        registeredAt: '21/09/2026 11:00',
        customerId: 'KH-VBSP-16',
        requester: 'Ngân hàng Chính sách xã hội Việt Nam',
        address: 'Tòa nhà CC5, Bán đảo Linh Đàm, phường Hoàng Liệt, quận Hoàng Mai, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '03 bản',
        quantity: 3,
        fee: 0,
        feeStatus: 'Miễn phí',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '21/09/2026 11:10',
        draftFile: ''
    },
    {
        id: 'BS-2026-000020',
        paperNo: 'PG-2026-020',
        registeredAt: '21/09/2026 14:20',
        customerId: 'KH-VDB-17',
        requester: 'Ngân hàng Phát triển Việt Nam - Sở giao dịch I',
        address: 'Số 185 phố Bà Triệu, phường Lê Đại Hành, quận Hai Bà Trưng, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '21/09/2026 14:30',
        draftFile: ''
    },
    {
        id: 'BS-2026-000021',
        paperNo: 'PG-2026-021',
        registeredAt: '20/09/2026 09:15',
        customerId: 'KH-SCB-18',
        requester: 'Ngân hàng TMCP Sài Gòn - Chi nhánh Hai Bà Trưng',
        address: 'Số 310 phố Huế, phường Phố Huế, quận Hai Bà Trưng, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '20/09/2026 09:25',
        draftFile: ''
    },
    {
        id: 'BS-2026-000022',
        paperNo: 'PG-2026-022',
        registeredAt: '20/09/2026 10:30',
        customerId: 'KH-NAB-19',
        requester: 'Ngân hàng TMCP Nam Á - Chi nhánh Đống Đa',
        address: 'Số 412 Tây Sơn, phường Thịnh Quang, quận Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao kèm thông báo về việc đăng ký thế chấp',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '20/09/2026 10:40',
        draftFile: ''
    },
    {
        id: 'BS-2026-000023',
        paperNo: 'PG-2026-023',
        registeredAt: '20/09/2026 14:00',
        customerId: 'KH-BVB-20',
        requester: 'Ngân hàng TMCP Bản Việt - Chi nhánh Cầu Giấy',
        address: 'Số 233 phố Cầu Giấy, phường Dịch Vọng, quận Cầu Giấy, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '01 bản',
        quantity: 1,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '20/09/2026 14:10',
        draftFile: ''
    },
    {
        id: 'BS-2026-000024',
        paperNo: 'PG-2026-024',
        registeredAt: '19/09/2026 09:00',
        customerId: 'KH-VIETABANK-21',
        requester: 'Ngân hàng TMCP Việt Á - PGD Khâm Thiên',
        address: 'Số 224 phố Khâm Thiên, phường Thổ Quan, quận Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '19/09/2026 09:10',
        draftFile: ''
    },
    {
        id: 'BS-2026-000025',
        paperNo: 'PG-2026-025',
        registeredAt: '19/09/2026 10:45',
        customerId: 'KH-NCB-22',
        requester: 'Ngân hàng TMCP Quốc Dân - PGD Thanh Xuân',
        address: 'Số 493 Nguyễn Trãi, phường Thanh Xuân Nam, quận Thanh Xuân, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Bị trả lại',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '19/09/2026 10:55',
        draftFile: '',
        returnReason: 'Số lượng bản sao yêu cầu vượt quá mức đăng ký thu phí ban đầu, yêu cầu đối soát lại biên lai thu phí.',
        returnedBy: 'Lê Hoàng Long - Giám đốc Trung tâm',
        returnedAt: '19/09/2026 14:00',
        returnHistory: [
            { reason: 'Số lượng bản sao yêu cầu vượt quá mức đăng ký thu phí ban đầu, yêu cầu đối soát lại biên lai thu phí.', by: 'Lê Hoàng Long - Giám đốc Trung tâm', at: '19/09/2026 14:00', resubmittedAt: '' },
            { reason: 'Cán bộ đính kèm nhầm bản scan đơn của hồ sơ khác.', by: 'Trần Thị Minh Nguyệt - Phó Giám đốc Trung tâm', at: '18/09/2026 16:15', resubmittedAt: '19/09/2026 09:30' }
        ]
    },
    {
        id: 'BS-2026-000026',
        paperNo: 'PG-2026-026',
        registeredAt: '18/09/2026 08:30',
        customerId: 'KH-KLB-23',
        requester: 'Ngân hàng TMCP Kiên Long - Chi nhánh Hà Nội',
        address: 'Số 68 Bà Triệu, phường Hàng Bài, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '18/09/2026 08:40',
        draftFile: ''
    },
    {
        id: 'BS-2026-000027',
        paperNo: 'PG-2026-027',
        registeredAt: '18/09/2026 14:15',
        customerId: 'KH-BAB-24',
        requester: 'Ngân hàng TMCP Bắc Á - PGD Kim Liên',
        address: 'Số 9 phố Đào Duy Anh, phường Phương Mai, quận Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '18/09/2026 14:25',
        draftFile: ''
    },
    {
        id: 'BS-2026-000028',
        paperNo: 'PG-2026-028',
        registeredAt: '17/09/2026 09:30',
        customerId: 'KH-PGB-25',
        requester: 'Ngân hàng TMCP Thịnh vượng và Phát triển (PGBank)',
        address: 'Tòa nhà Mipec, 229 Tây Sơn, Ngã Tư Sở, Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ giải quyết',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '17/09/2026 09:40',
        draftFile: ''
    },
    {
        id: 'BS-2026-000029',
        paperNo: 'PG-2026-029',
        registeredAt: '16/09/2026 10:00',
        customerId: 'KH-SAIGONBANK-26',
        requester: 'Ngân hàng TMCP Sài Gòn Công Thương - Chi nhánh Hà Nội',
        address: 'Số 14 phố Lê Đại Hành, phường Lê Đại Hành, quận Hai Bà Trưng, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '01 bản',
        quantity: 1,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Duyệt chờ ký',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '16/09/2026 10:10',
        draftFile: ''
    },
    {
        id: 'BS-2026-000030',
        paperNo: 'PG-2026-030',
        registeredAt: '15/09/2026 11:20',
        customerId: 'KH-BIDC-27',
        requester: 'Ngân hàng Đầu tư và Phát triển Campuchia - Chi nhánh Hà Nội',
        address: 'Số 10A phố Dã Tượng, phường Trần Hưng Đạo, quận Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ ký',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '15/09/2026 11:30',
        draftFile: ''
    },
    {
        id: 'BS-2026-000031',
        paperNo: 'PG-2026-031',
        registeredAt: '15/09/2026 14:10',
        customerId: 'KH-VCB-01',
        requester: 'Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)',
        address: '198 Trần Quang Khải, Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Chờ ký',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '15/09/2026 14:20',
        draftFile: ''
    },
    {
        id: 'BS-2026-000032',
        paperNo: '',
        registeredAt: '16/09/2026 09:15',
        customerId: 'KH-BIDV-02',
        requester: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)',
        address: '35 Hàng Vôi, Hoàn Kiếm, TP Hà Nội',
        source: 'Website khách hàng',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Chờ ký',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '16/09/2026 09:25',
        draftFile: ''
    },
    {
        id: 'BS-2026-000033',
        paperNo: '',
        registeredAt: '16/09/2026 10:45',
        customerId: 'KH-HOANGGIA-01',
        requester: 'Công ty TNHH Thương mại Hoàng Gia',
        address: 'Số 15 phố Bà Triệu, Hàng Bài, Hoàn Kiếm, TP Hà Nội',
        source: 'Website khách hàng',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Hoàn thành',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '16/09/2026 11:00',
        draftFile: ''
    },
    {
        id: 'BS-2026-000034',
        paperNo: 'PG-2026-034',
        registeredAt: '17/09/2026 09:20',
        customerId: 'KH-DAO-02',
        requester: 'Ông Trần Quang Đạo',
        address: 'Số 45 phố Lý Thường Kiệt, Hàng Bài, Hoàn Kiếm, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170855',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '01 bản',
        quantity: 1,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Hoàn thành',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '17/09/2026 09:30',
        draftFile: ''
    },
    {
        id: 'BS-2026-000035',
        paperNo: '',
        registeredAt: '18/09/2026 14:00',
        customerId: 'KH-BIENDONG-05',
        requester: 'Công ty Cổ phần Vận tải Biển Đông',
        address: 'Số 88 phố Lê Duẩn, Văn Miếu, Đống Đa, TP Hà Nội',
        source: 'Website khách hàng',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Bị từ chối',
        rejectReason: 'Không tìm thấy hồ sơ gốc tương ứng với số đăng ký yêu cầu.',
        rejectedBy: 'Nguyễn Văn Cán Bộ',
        rejectedAt: '18/09/2026 14:30',
        rejectLeader: 'Lê Hoàng Long - Giám đốc Trung tâm',
        rejectDraftFile: 'Van_ban_tu_choi_cap_ban_sao_BS2026000035_Signed.pdf',
        rejectFile: 'Bien_ban_kiem_tra_ho_so_goc.pdf',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '18/09/2026 14:10',
        draftFile: ''
    },
    {
        id: 'BS-2026-000036',
        paperNo: 'PG-2026-036',
        registeredAt: '19/09/2026 11:30',
        customerId: 'KH-MB-03',
        requester: 'Ngân hàng TMCP Quân đội (MB)',
        address: 'Số 21 Cát Linh, Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Đã duyệt - chờ trả kết quả',
        approvedAt: '19/09/2026 14:00',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '19/09/2026 11:45',
        draftFile: ''
    },
    {
        id: 'BS-2026-000037',
        paperNo: 'PG-2026-037',
        registeredAt: '20/09/2026 16:15',
        customerId: 'KH-TANTIEN-07',
        requester: 'Công ty TNHH Sản xuất Tân Tiến',
        address: 'Số 102 phố Thái Hà, Trung Liệt, Đống Đa, TP Hà Nội',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '01 bản',
        quantity: 1,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Đã duyệt - chờ trả kết quả',
        approvedAt: '20/09/2026 17:00',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '20/09/2026 16:30',
        draftFile: ''
    },
    {
        id: 'BS-2026-000038',
        paperNo: 'PG-2026-038',
        registeredAt: '21/09/2026 14:10',
        customerId: 'KH-VIB-02',
        requester: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)',
        address: 'Tòa nhà VIB, 111 Pasteur, Q.1, TP.HCM',
        source: 'Cán bộ nhập liệu',
        registrationNo: '1505170802',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao giấy',
        copyQty: '02 bản',
        quantity: 2,
        fee: 60000,
        feeStatus: 'Đã thu',
        status: 'Bị từ chối',
        rejectReason: 'Hồ sơ đăng ký gốc thuộc danh mục tài sản đặc biệt không thuộc thẩm quyền cấp bản sao của Trung tâm.',
        rejectedBy: 'Trần Thị Thu Trang',
        rejectedAt: '21/09/2026 15:45',
        rejectLeader: 'Lê Hoàng Long - Giám đốc Trung tâm',
        rejectDraftFile: 'Van_ban_tu_choi_cap_ban_sao_BS2026000038_Signed.pdf',
        rejectFile: 'Phieu_chuyen_ho_so_tham_quyen.pdf',
        receptionOfficer: 'Trần Thị Thu Trang',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '21/09/2026 14:20',
        draftFile: ''
    },
    {
        id: 'BS-2026-000039',
        paperNo: 'PG-2026-039',
        registeredAt: '22/09/2026 08:50',
        customerId: 'KH-HUNG-02',
        requester: 'Ông Nguyễn Văn Hùng',
        address: 'Số 12 phố Duy Tân, phường Dịch Vọng Hậu, Hà Nội',
        source: 'Website khách hàng',
        registrationNo: '1505156438',
        requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
        copyType: 'Bản sao điện tử',
        copyQty: '—',
        quantity: null,
        fee: 30000,
        feeStatus: 'Đã thu',
        status: 'Bị từ chối',
        rejectReason: 'Đơn yêu cầu cấp bản sao không có chữ ký, con dấu hợp lệ của người yêu cầu theo quy định của Nghị định 99/2022/NĐ-CP.',
        rejectedBy: 'Nguyễn Thị Tiếp Nhận',
        rejectedAt: '22/09/2026 09:20',
        rejectLeader: 'Lê Hoàng Long - Giám đốc Trung tâm',
        rejectDraftFile: 'Van_ban_tu_choi_cap_ban_sao_BS2026000039_Signed.pdf',
        rejectFile: 'Ban_chup_don_yeu_cau_thieu_chu_ky.pdf',
        receptionOfficer: 'Nguyễn Thị Tiếp Nhận',
        officer: 'Nguyễn Văn Cán Bộ',
        paidAt: '22/09/2026 09:00',
        draftFile: ''
    }
];

// Hồ sơ Yêu cầu cung cấp bản sao trực tuyến (Khách hàng gửi qua Website) phục vụ MH01 - Danh sách chờ duyệt
// và hồ sơ Bản sao giấy "Đã duyệt - chờ trả kết quả" phục vụ Xác nhận trả kết quả (MH05)
(function seedOnlineCopyRequests() {
    const requesters = [
        ['Công ty TNHH Thương mại Hoàng Gia', 'KH-HOANGGIA-01'], ['Ông Trần Quang Đạo', 'KH-DAO-02'], ['Ngân hàng TMCP Quân đội (MB)', 'KH-MB-03'],
        ['Bà Lê Thị Thanh Hương', 'KH-HUONG-04'], ['Công ty Cổ phần Vận tải Biển Đông', 'KH-BIENDONG-05'], ['Ông Phạm Văn Khánh', 'KH-KHANH-06'],
        ['Công ty TNHH Sản xuất Tân Tiến', 'KH-TANTIEN-07'], ['Bà Đinh Thị Mai Phương', 'KH-PHUONG-08']
    ];
    const regNos = ['1505156438', '1505170855', '1505170802'];
    const today = new Date();
    const pad = n => String(n).padStart(2, '0');
    requesters.forEach(([name, cid], i) => {
        const day = Math.max(1, Math.min(today.getDate(), 1 + i * 3));
        const isPaper = i % 3 === 1;
        officerCopyRequests.push({
            id: `BS-2026-1${pad(i + 1)}001`,
            paperNo: '',
            registeredAt: `${pad(day)}/${pad(today.getMonth() + 1)}/${today.getFullYear()} ${pad(8 + i)}:${pad((i * 13) % 60)}`,
            customerId: cid,
            requester: name,
            address: 'Hà Nội',
            source: 'Website khách hàng',
            registrationNo: regNos[i % regNos.length],
            requestType: 'Yêu cầu cung cấp bản sao văn bản chứng nhận đăng ký biện pháp bảo đảm',
            copyType: isPaper ? 'Bản sao giấy' : 'Bản sao điện tử',
            quantity: isPaper ? (i % 2) + 1 : null,
            fee: 30000,
            feeStatus: 'Đã thu',
            status: i < 6 ? 'Chờ duyệt' : 'Đã duyệt - chờ trả kết quả',
            officer: i < 6 ? '' : 'Nguyễn Văn Cán Bộ',
            ...(i >= 6 ? { copyType: 'Bản sao giấy', quantity: 2, approvedAt: `${pad(day)}/${pad(today.getMonth() + 1)}/${today.getFullYear()} 15:30` } : {})
        });
    });
})();
// Đồng bộ trạng thái hồ sơ bản sao đã xử lý tại màn Nhập liệu (nhap_lieu_ho_so_giay.html) về danh sách
const COPY_STORAGE_KEY = 'officer_copy_requests';
(function syncOfficerCopyRequestsFromStorage() {
    let stored = [];
    try { stored = JSON.parse(localStorage.getItem(COPY_STORAGE_KEY) || '[]'); } catch (err) { stored = []; }
    stored.forEach(s => {
        const item = officerCopyRequests.find(x => x.id === s.id);
        if (!item) return;
        if (s.status) item.status = s.status;
        if (s.originalRegistrationNo) item.registrationNo = s.originalRegistrationNo;
        if (s.handlingOfficer && s.status !== 'Chờ giải quyết') item.officer = s.handlingOfficer;
        if (s.registeredAtOfficial) item.registeredAtOfficial = s.registeredAtOfficial;
        if (s.rejectReason) item.rejectReason = s.rejectReason;
        if (s.rejectedAt) item.rejectedAt = s.rejectedAt;
    });
})();


// Đồng bộ trạng thái hồ sơ Yêu cầu cung cấp thông tin đã xử lý (lưu localStorage) về danh sách
// Dời Thời điểm đăng ký của dữ liệu giả lập CCTT & Bản sao về tháng hiện tại để nằm trong khoảng lọc mặc định (từ ngày 01 đến ngày hiện tại)
(function shiftServiceMockDatesToCurrentMonth() {
    const today = new Date();
    const pad = n => String(n).padStart(2, '0');
    const curMonth = pad(today.getMonth() + 1);
    const curYear = today.getFullYear();
    const maxDay = Math.max(1, today.getDate());

    (typeof ccttOfficerRequests !== 'undefined' ? ccttOfficerRequests : []).forEach((x, i) => {
        const m = String(x.registeredAt || '').match(/(\d{2}):(\d{2})/);
        const day = pad((i % maxDay) + 1);
        x.registeredAt = `${day}/${curMonth}/${curYear} ${m ? m[1] + ':' + m[2] : '09:00'}`;
        if (x.returnedAt) {
            const tm = String(x.returnedAt).match(/(\d{2}):(\d{2})/);
            x.returnedAt = `${day}/${curMonth}/${curYear} ${tm ? tm[1] + ':' + tm[2] : '14:15'}`;
        }
        if (x.rejectedAt) {
            const tm = String(x.rejectedAt).match(/(\d{2}):(\d{2})/);
            x.rejectedAt = `${day}/${curMonth}/${curYear} ${tm ? tm[1] + ':' + tm[2] : '16:00'}`;
        }
    });

    (typeof officerCopyRequests !== 'undefined' ? officerCopyRequests : []).forEach((x, i) => {
        const m = String(x.registeredAt || '').match(/(\d{2}):(\d{2})/);
        const day = pad((i % maxDay) + 1);
        x.registeredAt = `${day}/${curMonth}/${curYear} ${m ? m[1] + ':' + m[2] : '09:15'}`;
        if (x.returnedAt) {
            const tm = String(x.returnedAt).match(/(\d{2}):(\d{2})/);
            x.returnedAt = `${day}/${curMonth}/${curYear} ${tm ? tm[1] + ':' + tm[2] : '10:15'}`;
        }
        if (x.rejectedAt) {
            const tm = String(x.rejectedAt).match(/(\d{2}):(\d{2})/);
            x.rejectedAt = `${day}/${curMonth}/${curYear} ${tm ? tm[1] + ':' + tm[2] : '14:30'}`;
        }
    });
})();
(function syncOfficerCcttRequestsFromStorage() {
    let stored = [];
    try { stored = JSON.parse(localStorage.getItem('officer_cctt_requests') || '[]'); } catch (err) { stored = []; }
    stored.forEach(s => {
        const item = (typeof ccttOfficerRequests !== 'undefined' ? ccttOfficerRequests : []).find(x => x.id === s.id);
        if (item) Object.keys(s).forEach(k => { if (s[k] !== undefined && s[k] !== null) item[k] = s[k]; });
    });
})();
