// Metadata definition for 12 system configuration UCs
const ucMetadata = {
    UC551: {
        code: 'UC551',
        title: 'Cấu hình quản lý chung API',
        desc: 'Quản lý các tham số kỹ thuật điều phối hoạt động của API gateway: xác thực, giới hạn lưu lượng, phiên bản, môi trường kết nối.',
        tab: 'Vận hành',
        hasList: true,
        filters: ['environment', 'auth_type', 'is_active'],
        fields: [
            { id: 'api_name', label: 'Tên API', type: 'text', required: true },
            { id: 'api_base_url', label: 'Base URL', type: 'text', required: true },
            { id: 'api_version', label: 'Phiên bản', type: 'text', required: true, defaultValue: 'v1' },
            { id: 'auth_type', label: 'Kiểu xác thực', type: 'select', options: ['API_KEY', 'OAUTH2', 'BASIC', 'JWT'], required: true, defaultValue: 'API_KEY' },
            { id: 'api_key', label: 'API Key', type: 'password', required: false, dependsOn: { field: 'auth_type', value: 'API_KEY' } },
            { id: 'client_id', label: 'Client ID', type: 'text', required: false, dependsOn: { field: 'auth_type', value: 'OAUTH2' } },
            { id: 'client_secret', label: 'Client Secret', type: 'password', required: false, dependsOn: { field: 'auth_type', value: 'OAUTH2' } },
            { id: 'token_url', label: 'Token URL', type: 'text', required: false, dependsOn: { field: 'auth_type', value: 'OAUTH2' } },
            { id: 'rate_limit', label: 'Giới hạn request/phút', type: 'number', required: true, defaultValue: 100 },
            { id: 'max_retry', label: 'Số lần retry', type: 'number', required: true, defaultValue: 3 },
            { id: 'retry_interval_ms', label: 'Khoảng cách retry (ms)', type: 'number', required: true, defaultValue: 1000 },
            { id: 'environment', label: 'Môi trường', type: 'select', options: ['DEV', 'UAT', 'PRODUCTION'], required: true, defaultValue: 'PRODUCTION' },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true },
            { id: 'description', label: 'Mô tả', type: 'textarea', required: false }
        ]
    },
    UC552: {
        code: 'UC552',
        title: 'Cấu hình quản lý tiến trình tự động',
        desc: 'Quản lý các job/scheduler chạy nền tự động trong hệ thống (batch xử lý, đồng bộ dữ liệu, gửi thông báo định kỳ...).',
        tab: 'Vận hành',
        hasList: true,
        filters: ['job_type', 'is_enabled'],
        fields: [
            { id: 'job_code', label: 'Mã tiến trình', type: 'text', required: true },
            { id: 'job_name', label: 'Tên tiến trình', type: 'text', required: true },
            { id: 'job_type', label: 'Loại tiến trình', type: 'select', options: ['CRON', 'INTERVAL', 'ONE_TIME'], required: true, defaultValue: 'CRON' },
            { id: 'cron_expression', label: 'Biểu thức Cron', type: 'text', required: false, dependsOn: { field: 'job_type', value: 'CRON' } },
            { id: 'interval_value', label: 'Khoảng thời gian', type: 'number', required: false, dependsOn: { field: 'job_type', value: 'INTERVAL' } },
            { id: 'interval_unit', label: 'Đơn vị', type: 'select', options: ['SECOND', 'MINUTE', 'HOUR', 'DAY'], required: false, defaultValue: 'MINUTE', dependsOn: { field: 'job_type', value: 'INTERVAL' } },
            { id: 'start_time', label: 'Thời gian bắt đầu', type: 'text', required: false, dependsOn: { field: 'job_type', value: 'ONE_TIME' } },
            { id: 'max_execution_time_s', label: 'Thời gian chạy tối đa (giây)', type: 'number', required: true, defaultValue: 300 },
            { id: 'on_failure_action', label: 'Khi lỗi', type: 'select', options: ['RETRY', 'ALERT', 'STOP', 'RETRY_THEN_ALERT'], required: true, defaultValue: 'ALERT' },
            { id: 'alert_email', label: 'Email cảnh báo', type: 'text', required: false },
            { id: 'is_enabled', label: 'Kích hoạt', type: 'switch', required: true, defaultValue: true },
            { id: 'description', label: 'Mô tả', type: 'textarea', required: false }
        ]
    },
    UC553: {
        code: 'UC553',
        title: 'Cấu hình thời gian chờ (Timeout)',
        desc: 'Thiết lập ngưỡng thời gian chờ cho từng loại kết nối và thao tác trong hệ thống, tránh treo request và chiếm dụng tài nguyên.',
        tab: 'Vận hành',
        hasList: true,
        filters: ['timeout_type', 'is_active'],
        fields: [
            { id: 'timeout_type', label: 'Loại timeout', type: 'select', options: ['API_CALL', 'DB_QUERY', 'SESSION', 'FILE_UPLOAD', 'REPORT_EXPORT', 'PAYMENT_GATEWAY'], required: true },
            { id: 'timeout_name', label: 'Tên timeout', type: 'text', required: true },
            { id: 'connect_timeout_ms', label: 'Timeout kết nối (ms)', type: 'number', required: true, defaultValue: 5000 },
            { id: 'read_timeout_ms', label: 'Timeout đọc dữ liệu (ms)', type: 'number', required: true, defaultValue: 30000 },
            { id: 'write_timeout_ms', label: 'Timeout ghi dữ liệu (ms)', type: 'number', required: true, defaultValue: 30000 },
            { id: 'session_timeout_min', label: 'Timeout phiên (phút)', type: 'number', required: false, defaultValue: 30 },
            { id: 'idle_timeout_min', label: 'Timeout không hoạt động (phút)', type: 'number', required: false, defaultValue: 15 },
            { id: 'apply_to', label: 'Áp dụng cho', type: 'select', options: ['ALL', 'PORTAL_CANBO', 'PORTAL_KHACHHANG', 'MOBILE_APP'], required: true, defaultValue: 'ALL' },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true },
            { id: 'note', label: 'Ghi chú', type: 'textarea', required: false }
        ]
    },
    UC554: {
        code: 'UC554',
        title: 'Cấu hình giới hạn địa chỉ mạng quản trị',
        desc: 'Thiết lập danh sách IP/dải IP được phép truy cập vào giao diện quản trị hệ thống (IP Whitelist), ngăn chặn truy cập trái phép từ mạng ngoài.',
        tab: 'Vận hành',
        hasList: true,
        filters: ['ip_type', 'is_active'],
        fields: [
            { id: 'rule_name', label: 'Tên quy tắc', type: 'text', required: true },
            { id: 'ip_type', label: 'Loại địa chỉ', type: 'select', options: ['SINGLE_IP', 'IP_RANGE', 'CIDR'], required: true, defaultValue: 'SINGLE_IP' },
            { id: 'ip_address', label: 'Địa chỉ IP', type: 'text', required: false, dependsOn: { field: 'ip_type', value: 'SINGLE_IP' } },
            { id: 'ip_from', label: 'IP bắt đầu', type: 'text', required: false, dependsOn: { field: 'ip_type', value: 'IP_RANGE' } },
            { id: 'ip_to', label: 'IP kết thúc', type: 'text', required: false, dependsOn: { field: 'ip_type', value: 'IP_RANGE' } },
            { id: 'cidr_notation', label: 'CIDR', type: 'text', required: false, dependsOn: { field: 'ip_type', value: 'CIDR' } },
            { id: 'apply_to_role', label: 'Áp dụng cho nhóm quyền', type: 'select', options: ['ALL', 'QTHT', 'CBPD', 'CBNV'], required: true, defaultValue: 'ALL' },
            { id: 'valid_from', label: 'Hiệu lực từ ngày', type: 'text', required: true },
            { id: 'valid_to', label: 'Hiệu lực đến ngày', type: 'text', required: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true },
            { id: 'description', label: 'Mô tả', type: 'textarea', required: false }
        ]
    },
    UC555: {
        code: 'UC555',
        title: 'Cấu hình thông tin email, địa chỉ, trang web',
        desc: 'Quản lý thông tin liên hệ và nhận diện của tổ chức, dùng cho header/footer email giao dịch, biểu mẫu xuất ra, trang web công khai.',
        tab: 'Tổ chức',
        hasList: false,
        fields: [
            { id: 'org_code', label: 'Mã đơn vị', type: 'text', required: true },
            { id: 'org_name', label: 'Tên đơn vị', type: 'text', required: true },
            { id: 'org_name_en', label: 'Tên tiếng Anh', type: 'text', required: false },
            { id: 'org_short_name', label: 'Tên viết tắt', type: 'text', required: false },
            { id: 'tax_code', label: 'Mã số thuế', type: 'text', required: true },
            { id: 'email_primary', label: 'Email chính', type: 'text', required: true },
            { id: 'email_noreply', label: 'Email no-reply', type: 'text', required: true },
            { id: 'email_support', label: 'Email hỗ trợ', type: 'text', required: false },
            { id: 'phone_primary', label: 'Số điện thoại chính', type: 'text', required: true },
            { id: 'phone_hotline', label: 'Hotline', type: 'text', required: false },
            { id: 'fax', label: 'Số fax', type: 'text', required: false },
            { id: 'address_full', label: 'Địa chỉ đầy đủ', type: 'text', required: true },
            { id: 'province_code', label: 'Tỉnh/Thành phố', type: 'select', required: true },
            { id: 'district_code', label: 'Quận/Huyện', type: 'select', required: true },
            { id: 'ward_code', label: 'Phường/Xã', type: 'select', required: false },
            { id: 'website_url', label: 'Website', type: 'text', required: false },
            { id: 'facebook_url', label: 'Facebook', type: 'text', required: false },
            { id: 'logo_path', label: 'Logo', type: 'file', required: false },
            { id: 'favicon_path', label: 'Favicon', type: 'file', required: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true }
        ]
    },
    UC556: {
        code: 'UC556',
        title: 'Cấu hình thông tin về người ký',
        desc: 'Quản lý danh sách người được uỷ quyền ký trên các văn bản, hợp đồng, biểu mẫu xuất từ hệ thống.',
        tab: 'Tổ chức',
        hasList: true,
        filters: ['sign_role', 'is_active'],
        fields: [
            { id: 'signer_code', label: 'Mã người ký', type: 'text', required: true },
            { id: 'signer_name', label: 'Họ tên người ký', type: 'text', required: true },
            { id: 'position', label: 'Chức vụ', type: 'text', required: true },
            { id: 'department', label: 'Phòng ban', type: 'text', required: false },
            { id: 'org_unit', label: 'Đơn vị áp dụng', type: 'select', options: ['Cục Đăng ký quốc gia giao dịch bảo đảm', 'Trung tâm Đăng ký giao dịch bảo đảm tại Hà Nội', 'Trung tâm Đăng ký giao dịch bảo đảm tại TP. Hồ Chí Minh', 'Trung tâm Đăng ký giao dịch bảo đảm tại Đà Nẵng'], required: true, defaultValue: 'Cục Đăng ký quốc gia giao dịch bảo đảm' },
            { id: 'sign_role', label: 'Vai trò ký', type: 'select', options: ['AUTHORIZED_SIGNER', 'PREPARER', 'REVIEWER', 'APPROVER'], required: true },
            { id: 'sign_position_on_doc', label: 'Vị trí in trên văn bản', type: 'select', options: ['TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT', 'CUSTOM'], required: true },
            { id: 'sign_label', label: 'Nhãn ký', type: 'text', required: true },
            { id: 'signature_image', label: 'Hình ảnh chữ ký', type: 'file', required: false },
            { id: 'effective_from', label: 'Hiệu lực từ', type: 'text', required: true },
            { id: 'effective_to', label: 'Hiệu lực đến', type: 'text', required: false },
            { id: 'apply_to_doc_type', label: 'Áp dụng cho loại văn bản', type: 'select', options: ['ALL', 'HOA_DON', 'CHUNG_THU_DK', 'BIEN_BAN_BAN_GIAO'], required: true, defaultValue: 'ALL' },
            { id: 'is_default', label: 'Mặc định', type: 'switch', required: false, defaultValue: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true }
        ]
    },
    UC557: {
        code: 'UC557',
        title: 'Cấu hình thông tin về con dấu',
        desc: 'Quản lý hình ảnh và thông tin con dấu của tổ chức để nhúng vào văn bản, hợp đồng xuất PDF.',
        tab: 'Tổ chức',
        hasList: true,
        filters: ['seal_type', 'is_active'],
        fields: [
            { id: 'seal_code', label: 'Mã con dấu', type: 'text', required: true },
            { id: 'seal_name', label: 'Tên con dấu', type: 'text', required: true },
            { id: 'seal_type', label: 'Loại dấu', type: 'select', options: ['ROUND_SEAL', 'TITLE_SEAL', 'BRANCH_SEAL', 'DIGITAL_SEAL'], required: true },
            { id: 'seal_image', label: 'Hình ảnh con dấu', type: 'file', required: true },
            { id: 'seal_position_on_doc', label: 'Vị trí trên văn bản', type: 'select', options: ['TOP_LEFT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT', 'OVERLAP_SIGNATURE', 'CUSTOM'], required: true, defaultValue: 'BOTTOM_LEFT' },
            { id: 'offset_x_mm', label: 'Dịch ngang (mm)', type: 'number', required: false, defaultValue: 0, dependsOn: { field: 'seal_position_on_doc', value: 'CUSTOM' } },
            { id: 'offset_y_mm', label: 'Dịch dọc (mm)', type: 'number', required: false, defaultValue: 0, dependsOn: { field: 'seal_position_on_doc', value: 'CUSTOM' } },
            { id: 'size_mm', label: 'Kích thước in (mm)', type: 'number', required: true, defaultValue: 40 },
            { id: 'opacity_percent', label: 'Độ trong suốt (%)', type: 'number', required: true, defaultValue: 80 },
            { id: 'apply_to_doc_type', label: 'Áp dụng cho loại văn bản', type: 'select', options: ['ALL', 'HOA_DON', 'CHUNG_THU_DK'], required: true, defaultValue: 'ALL' },
            { id: 'effective_from', label: 'Hiệu lực từ', type: 'text', required: true },
            { id: 'effective_to', label: 'Hiệu lực đến', type: 'text', required: false },
            { id: 'is_default', label: 'Mặc định', type: 'switch', required: false, defaultValue: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true }
        ]
    },
    UC558: {
        code: 'UC558',
        title: 'Cấu hình thông tin về tài khoản thanh toán',
        desc: 'Quản lý danh sách tài khoản ngân hàng của tổ chức dùng để in trên hoá đơn, hợp đồng, thông báo thu phí.',
        tab: 'Tài chính',
        hasList: true,
        filters: ['currency', 'account_type', 'is_active'],
        fields: [
            { id: 'account_code', label: 'Mã tài khoản', type: 'text', required: true },
            { id: 'org_unit', label: 'Đơn vị quản lý tài khoản', type: 'select', options: ['Cục Đăng ký quốc gia giao dịch bảo đảm', 'Trung tâm Đăng ký giao dịch bảo đảm tại Hà Nội', 'Trung tâm Đăng ký giao dịch bảo đảm tại TP. Hồ Chí Minh', 'Trung tâm Đăng ký giao dịch bảo đảm tại Đà Nẵng'], required: true, defaultValue: 'Cục Đăng ký quốc gia giao dịch bảo đảm' },
            { id: 'account_holder', label: 'Tên chủ tài khoản', type: 'text', required: true },
            { id: 'account_number', label: 'Số tài khoản', type: 'text', required: true },
            { id: 'bank_code', label: 'Ngân hàng', type: 'select', options: ['VCB', 'BIDV', 'VIETINBANK', 'AGRIBANK', 'TECHCOMBANK'], required: true },
            { id: 'bank_branch', label: 'Chi nhánh', type: 'text', required: false },
            { id: 'bank_province', label: 'Tỉnh/Thành phố NH', type: 'select', options: ['Hà Nội', 'TP. Hồ Chí Minh', 'Đà Nẵng'], required: false },
            { id: 'currency', label: 'Loại tiền tệ', type: 'select', options: ['VND', 'USD', 'EUR'], required: true, defaultValue: 'VND' },
            { id: 'account_type', label: 'Loại tài khoản', type: 'select', options: ['PAYMENT', 'DEPOSIT', 'FOREIGN_CURRENCY'], required: true },
            { id: 'swift_code', label: 'SWIFT Code', type: 'text', required: false, dependsOn: { field: 'currency', value: 'USD' } },
            { id: 'apply_to_doc_type', label: 'Áp dụng cho loại chứng từ', type: 'select', options: ['ALL', 'HOA_DON', 'THONG_BAO_PHI'], required: true, defaultValue: 'ALL' },
            { id: 'effective_from', label: 'Hiệu lực từ', type: 'text', required: true },
            { id: 'effective_to', label: 'Hiệu lực đến', type: 'text', required: false },
            { id: 'is_default', label: 'Mặc định', type: 'switch', required: false, defaultValue: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true },
            { id: 'note', label: 'Ghi chú', type: 'textarea', required: false }
        ]
    },
    UC559: {
        code: 'UC559',
        title: 'Cấu hình thông tin về biểu phí',
        desc: 'Quản lý biểu phí dịch vụ áp dụng trong hệ thống — cơ sở để tính tiền trên hóa đơn, hợp đồng và thông báo thu phí.',
        tab: 'Tài chính',
        hasList: true,
        filters: ['fee_category', 'calculation_method', 'is_active'],
        fields: [
            { id: 'fee_code', label: 'Mã phí', type: 'text', required: true },
            { id: 'fee_name', label: 'Tên phí', type: 'text', required: true },
            { id: 'fee_category', label: 'Nhóm phí', type: 'select', options: ['PHAN_HE_GDBD', 'PHAN_HE_BTNN', 'DICH_VU_CONG_KHAC'], required: true },
            { id: 'calculation_method', label: 'Phương thức tính', type: 'select', options: ['FIXED', 'PERCENTAGE', 'TIERED', 'FORMULA'], required: true },
            { id: 'fee_amount', label: 'Mức phí (VND)', type: 'number', required: false, dependsOn: { field: 'calculation_method', value: 'FIXED' } },
            { id: 'fee_percentage', label: 'Tỷ lệ phí (%)', type: 'number', required: false, dependsOn: { field: 'calculation_method', value: 'PERCENTAGE' } },
            { id: 'percentage_base', label: 'Tính % trên', type: 'select', options: ['TRANSACTION_VALUE', 'LOAN_AMOUNT', 'ASSET_VALUE'], required: false, dependsOn: { field: 'calculation_method', value: 'PERCENTAGE' } },
            { id: 'min_fee', label: 'Phí tối thiểu', type: 'number', required: false },
            { id: 'max_fee', label: 'Phí tối đa', type: 'number', required: false },
            { id: 'tiered_config', label: 'Cấu hình bậc thang', type: 'textarea', required: false, dependsOn: { field: 'calculation_method', value: 'TIERED' } },
            { id: 'currency', label: 'Tiền tệ', type: 'select', options: ['VND', 'USD'], required: true, defaultValue: 'VND' },
            { id: 'vat_rate', label: 'Thuế VAT (%)', type: 'select', options: ['0', '5', '8', '10'], required: true, defaultValue: '10' },
            { id: 'effective_from', label: 'Hiệu lực từ', type: 'text', required: true },
            { id: 'effective_to', label: 'Hiệu lực đến', type: 'text', required: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true }
        ]
    },
    UC560: {
        code: 'UC560',
        title: 'Cấu hình thông tin kiểm tra',
        desc: 'Thiết lập các quy tắc kiểm tra/validation được áp dụng tự động trong quy trình nghiệp vụ — kiểm tra hồ sơ, điều kiện xét duyệt.',
        tab: 'Tài chính',
        hasList: true,
        filters: ['check_type', 'is_active'],
        fields: [
            { id: 'check_code', label: 'Mã kiểm tra', type: 'text', required: true },
            { id: 'check_name', label: 'Tên kiểm tra', type: 'text', required: true },
            { id: 'check_group', label: 'Nhóm kiểm tra', type: 'select', options: ['HOSODB', 'TAISANDB', 'NANG_LUC_PHAP_LY', 'PHI_THU_TUC'], required: true },
            { id: 'apply_to_process', label: 'Áp dụng cho quy trình', type: 'select', options: ['DANG_KY_BPBD', 'SUA_DOI_BPBD', 'XOA_DANG_KY', 'CAP_CHUNG_THU'], required: true },
            { id: 'check_type', label: 'Loại kiểm tra', type: 'select', options: ['MANDATORY_BLOCK', 'MANDATORY_WARN', 'OPTIONAL'], required: true },
            { id: 'condition_expression', label: 'Biểu thức điều kiện', type: 'textarea', required: true },
            { id: 'error_message_vi', label: 'Thông báo lỗi (VI)', type: 'text', required: true },
            { id: 'error_message_en', label: 'Thông báo lỗi (EN)', type: 'text', required: false },
            { id: 'check_order', label: 'Thứ tự kiểm tra', type: 'number', required: true, defaultValue: 99 },
            { id: 'effective_from', label: 'Hiệu lực từ', type: 'text', required: true },
            { id: 'effective_to', label: 'Hiệu lực đến', type: 'text', required: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true }
        ]
    },
    UC561: {
        code: 'UC561',
        title: 'Cấu hình các tham số khác của hệ thống',
        desc: 'Kho tham số hệ thống dạng key-value linh hoạt, dành cho các giá trị cấu hình không thuộc các UC chuyên biệt khác.',
        tab: 'Khác',
        hasList: true,
        filters: ['param_group', 'param_type', 'is_active'],
        fields: [
            { id: 'param_key', label: 'Khoá tham số', type: 'text', required: true },
            { id: 'param_value', label: 'Giá trị', type: 'textarea', required: true },
            { id: 'param_type', label: 'Kiểu dữ liệu', type: 'select', options: ['STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'ENCRYPTED'], required: true, defaultValue: 'STRING' },
            { id: 'param_group', label: 'Nhóm tham số', type: 'select', options: ['EMAIL', 'STORAGE', 'NOTIFICATION', 'UI', 'INTEGRATION', 'OTHER'], required: true },
            { id: 'display_name', label: 'Tên hiển thị', type: 'text', required: true },
            { id: 'description', label: 'Mô tả', type: 'textarea', required: false },
            { id: 'default_value', label: 'Giá trị mặc định', type: 'text', required: false },
            { id: 'is_sensitive', label: 'Dữ liệu nhạy cảm', type: 'switch', required: true, defaultValue: false },
            { id: 'is_readonly', label: 'Chỉ đọc', type: 'switch', required: true, defaultValue: false },
            { id: 'requires_restart', label: 'Cần khởi động lại', type: 'switch', required: true, defaultValue: false },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true }
        ]
    },
    UC562: {
        code: 'UC562',
        title: 'Thiết lập cơ chế bảo mật đa nhân tố (MFA)',
        desc: 'Cấu hình chính sách xác thực đa nhân tố (Multi-Factor Authentication) cho hệ thống — loại phương thức, đối tượng áp dụng.',
        tab: 'Khác',
        hasList: true,
        filters: ['enforcement_level', 'is_active'],
        fields: [
            { id: 'policy_name', label: 'Tên chính sách', type: 'text', required: true },
            { id: 'mfa_methods', label: 'Phương thức MFA', type: 'text', required: true },
            { id: 'apply_to_role', label: 'Áp dụng cho nhóm quyền', type: 'text', required: true },
            { id: 'enforcement_level', label: 'Mức độ bắt buộc', type: 'select', options: ['MANDATORY', 'OPTIONAL', 'DISABLED'], required: true },
            { id: 'effective_from', label: 'Hiệu lực từ', type: 'text', required: true },
            { id: 'is_active', label: 'Trạng thái', type: 'switch', required: true, defaultValue: true }
        ]
    }
};

// 10 Mock records for each Use Case to fulfill the "tối thiểu 10 bản ghi" rule
const mockRecords = {
    UC551: [
        { id: '1', api_name: 'Vietcombank Payment API', api_base_url: 'https://api.vietcombank.com.vn/payment/v1', api_version: 'v1.2', auth_type: 'OAUTH2', client_id: 'vcb_client_prod', client_secret: '••••••••', token_url: 'https://api.vietcombank.com.vn/oauth/token', rate_limit: 1000, max_retry: 3, retry_interval_ms: 1000, environment: 'PRODUCTION', is_active: true, description: 'Cổng kết nối thanh toán phí trực tuyến ngân hàng Vietcombank.' },
        { id: '2', api_name: 'BIDV Reconciliation API', api_base_url: 'https://api.bidv.com.vn/reconcile', api_version: 'v1.0', auth_type: 'API_KEY', api_key: '••••••••', rate_limit: 500, max_retry: 2, retry_interval_ms: 2000, environment: 'PRODUCTION', is_active: true, description: 'Đối soát luồng tiền nộp phí giao dịch hàng ngày của BIDV.' },
        { id: '3', api_name: 'Napas Gateway Connect', api_base_url: 'https://sandbox.napas.com.vn/gateway', api_version: 'v2.0', auth_type: 'JWT', rate_limit: 2000, max_retry: 5, retry_interval_ms: 500, environment: 'UAT', is_active: true, description: 'Kênh tích hợp thẻ nội địa Napas môi trường UAT.' },
        { id: '4', api_name: 'SMS OTP Brandname API', api_base_url: 'https://api.viettel.vn/sms/brandname', api_version: 'v1.0', auth_type: 'BASIC', rate_limit: 300, max_retry: 3, retry_interval_ms: 1500, environment: 'PRODUCTION', is_active: true, description: 'API gửi tin nhắn SMS OTP thương hiệu Cục ĐKBPBĐ.' },
        { id: '5', api_name: 'Cơ sở dữ liệu Dân cư Quốc gia', api_base_url: 'https://vnconnect.gov.vn/api/dan-cu', api_version: 'v3.0', auth_type: 'OAUTH2', client_id: 'gdbd_agency_01', client_secret: '••••••••', token_url: 'https://vnconnect.gov.vn/oauth/token', rate_limit: 5000, max_retry: 3, retry_interval_ms: 1000, environment: 'PRODUCTION', is_active: true, description: 'API liên thông xác thực định danh cá nhân Bộ Công an.' },
        { id: '6', api_name: 'Cơ sở dữ liệu Doanh nghiệp Quốc gia', api_base_url: 'https://api.mpi.gov.vn/enterprise', api_version: 'v1.1', auth_type: 'API_KEY', api_key: '••••••••', rate_limit: 2000, max_retry: 3, retry_interval_ms: 1000, environment: 'PRODUCTION', is_active: true, description: 'API tra cứu thông tin đăng ký kinh doanh doanh nghiệp.' },
        { id: '7', api_name: 'Báo cáo Thuế Điện tử', api_base_url: 'https://api.gdt.gov.vn/check-tax', api_version: 'v1.0', auth_type: 'BASIC', rate_limit: 800, max_retry: 2, retry_interval_ms: 2000, environment: 'PRODUCTION', is_active: false, description: 'Kiểm tra thông tin nộp thuế doanh nghiệp bên thế chấp.' },
        { id: '8', api_name: 'Email SMTP Sendgrid', api_base_url: 'https://api.sendgrid.com/v3', api_version: 'v3.0', auth_type: 'API_KEY', api_key: '••••••••', rate_limit: 10000, max_retry: 4, retry_interval_ms: 500, environment: 'PRODUCTION', is_active: true, description: 'API gửi email thông báo kết quả giao dịch tự động.' },
        { id: '9', api_name: 'VNPT SmartCA Sign Service', api_base_url: 'https://smartca.vnpt.vn/sign', api_version: 'v2.1', auth_type: 'OAUTH2', client_id: 'gdbd_smartca', client_secret: '••••••••', token_url: 'https://smartca.vnpt.vn/oauth/token', rate_limit: 3000, max_retry: 3, retry_interval_ms: 1000, environment: 'PRODUCTION', is_active: true, description: 'API ký số từ xa ký duyệt chứng nhận đăng ký biện pháp bảo đảm.' },
        { id: '10', api_name: 'Đăng kiểm Phương tiện giao thông', api_base_url: 'https://dev.vr.org.vn/api/vehicles', api_version: 'v1.0', auth_type: 'API_KEY', api_key: '••••••••', rate_limit: 100, max_retry: 2, retry_interval_ms: 3000, environment: 'DEV', is_active: true, description: 'Tra cứu thông tin số khung số máy ô tô, xe máy.' }
    ],
    UC552: [
        { id: '1', job_code: 'LOG_PURGE_JOB', job_name: 'Dọn dẹp nhật ký hệ thống cũ', job_type: 'CRON', cron_expression: '0 0 1 * * ?', max_execution_time_s: 3600, on_failure_action: 'ALERT', alert_email: 'admin@btp.gov.vn', is_enabled: true, description: 'Purge log quá 90 ngày vào 1 giờ sáng hàng ngày.', last_run_at: '25/06/2026 01:00', last_run_status: 'SUCCESS' },
        { id: '2', job_code: 'EMAIL_NOTIFY_BATCH', job_name: 'Tiến trình gửi email thông báo hàng loạt', job_type: 'INTERVAL', interval_value: 5, interval_unit: 'MINUTE', max_execution_time_s: 240, on_failure_action: 'RETRY', is_enabled: true, description: 'Quét hàng đợi thông báo email gửi đi 5 phút 1 lần.', last_run_at: '25/06/2026 18:30', last_run_status: 'SUCCESS' },
        { id: '3', job_code: 'PAYMENT_RECONCILE', job_name: 'Đối soát giao dịch thanh toán ngân hàng', job_type: 'CRON', cron_expression: '0 30 23 * * ?', max_execution_time_s: 1800, on_failure_action: 'RETRY_THEN_ALERT', alert_email: 'finance_ops@btp.gov.vn;admin@btp.gov.vn', is_enabled: true, description: 'Đối soát luồng tiền nộp phí giao dịch lúc 23:30 hàng ngày.', last_run_at: '24/06/2026 23:30', last_run_status: 'SUCCESS' },
        { id: '4', job_code: 'SMS_OTP_CLEANUP', job_name: 'Dọn dẹp OTP hết hạn', job_type: 'INTERVAL', interval_value: 1, interval_unit: 'HOUR', max_execution_time_s: 60, on_failure_action: 'STOP', is_enabled: true, description: 'Dọn dẹp mã SMS OTP hết hạn khỏi RAM/Database.', last_run_at: '25/06/2026 18:00', last_run_status: 'SUCCESS' },
        { id: '5', job_code: 'DB_DAILY_BACKUP', job_name: 'Sao lưu cơ sở dữ liệu hàng ngày', job_type: 'CRON', cron_expression: '0 0 2 * * ?', max_execution_time_s: 7200, on_failure_action: 'ALERT', alert_email: 'sysadmin@btp.gov.vn', is_enabled: true, description: 'Tự động backup DB nén đẩy lên Cloud Object Storage.', last_run_at: '25/06/2026 02:00', last_run_status: 'SUCCESS' },
        { id: '6', job_code: 'EXPIRED_CERT_ALERT', job_name: 'Quét và cảnh báo chữ ký số sắp hết hạn', job_type: 'CRON', cron_expression: '0 0 8 * * ?', max_execution_time_s: 600, on_failure_action: 'ALERT', alert_email: 'contact@btp.gov.vn', is_enabled: true, description: 'Kiểm tra người dùng có chữ ký số hết hạn trong 30 ngày tới.', last_run_at: '25/06/2026 08:00', last_run_status: 'SUCCESS' },
        { id: '7', job_code: 'PORTAL_CACHE_EVICT', job_name: 'Đồng bộ hóa cache hệ thống', job_type: 'INTERVAL', interval_value: 30, interval_unit: 'MINUTE', max_execution_time_s: 180, on_failure_action: 'STOP', is_enabled: true, description: 'Làm mới cache cấu hình và danh mục tỉnh thành.', last_run_at: '25/06/2026 18:05', last_run_status: 'SUCCESS' },
        { id: '8', job_code: 'MONTHLY_REPORT_GEN', job_name: 'Khởi tạo báo cáo thống kê tháng', job_type: 'CRON', cron_expression: '0 0 3 1 * ?', max_execution_time_s: 14400, on_failure_action: 'ALERT', alert_email: 'boss@btp.gov.vn', is_enabled: true, description: 'Chạy lúc 3h sáng ngày đầu tháng để tổng hợp dữ liệu thống kê.', last_run_at: '01/06/2026 03:00', last_run_status: 'SUCCESS' },
        { id: '9', job_code: 'CRM_CONTACT_SYNC', job_name: 'Đồng bộ danh sách doanh nghiệp', job_type: 'INTERVAL', interval_value: 12, interval_unit: 'HOUR', max_execution_time_s: 900, on_failure_action: 'ALERT', alert_email: 'ops@btp.gov.vn', is_enabled: false, description: 'Đồng bộ thông tin đăng ký doanh nghiệp liên thông.', last_run_at: '25/06/2026 06:00', last_run_status: 'FAILED' },
        { id: '10', job_code: 'TEMP_FILE_CLEANER', job_name: 'Dọn dẹp thư mục tạm thời', job_type: 'CRON', cron_expression: '0 0 4 * * ?', max_execution_time_s: 300, on_failure_action: 'STOP', is_enabled: true, description: 'Xóa tệp excel/pdf tạm sinh ra trong lúc in xuất báo cáo.', last_run_at: '25/06/2026 04:00', last_run_status: 'SUCCESS' }
    ],
    UC553: [
        { id: '1', timeout_type: 'API_CALL', timeout_name: 'Timeout kết nối API liên thông dân cư', connect_timeout_ms: 3000, read_timeout_ms: 10000, write_timeout_ms: 10000, apply_to: 'ALL', is_active: true, note: 'Khống chế thời gian chờ khi gọi API xác thực dân cư của Bộ Công an.' },
        { id: '2', timeout_type: 'DB_QUERY', timeout_name: 'Thời gian chờ truy vấn báo cáo nặng', connect_timeout_ms: 5000, read_timeout_ms: 180000, write_timeout_ms: 180000, apply_to: 'PORTAL_CANBO', is_active: true, note: 'Thời gian tối đa để chạy một câu SQL báo cáo tổng hợp trước khi tự hủy.' },
        { id: '3', timeout_type: 'SESSION', timeout_name: 'Phiên làm việc Cán bộ trực tuyến', connect_timeout_ms: 1000, read_timeout_ms: 5000, session_timeout_min: 60, idle_timeout_min: 15, apply_to: 'PORTAL_CANBO', is_active: true, note: 'Nếu cán bộ không tương tác trong 15 phút sẽ tự động Logout.' },
        { id: '4', timeout_type: 'SESSION', timeout_name: 'Phiên làm việc Khách hàng trực tuyến', connect_timeout_ms: 1000, read_timeout_ms: 5000, session_timeout_min: 120, idle_timeout_min: 30, apply_to: 'PORTAL_KHACHHANG', is_active: true, note: 'Phiên làm việc của công dân kê khai hồ sơ.' },
        { id: '5', timeout_type: 'FILE_UPLOAD', timeout_name: 'Timeout tải lên file đính kèm hồ sơ', connect_timeout_ms: 5000, read_timeout_ms: 120000, write_timeout_ms: 120000, apply_to: 'ALL', is_active: true, note: 'Áp dụng khi tải lên tài liệu đính kèm dung lượng lớn đến 20MB.' },
        { id: '6', timeout_type: 'PAYMENT_GATEWAY', timeout_name: 'Timeout chờ giao dịch thẻ Napas', connect_timeout_ms: 5000, read_timeout_ms: 60000, write_timeout_ms: 60000, apply_to: 'PORTAL_KHACHHANG', is_active: true, note: 'Thời gian tối đa chờ khách hàng hoàn thành nhập thông tin thẻ.' },
        { id: '7', timeout_type: 'API_CALL', timeout_name: 'Timeout API tra cứu số khung số máy', connect_timeout_ms: 2000, read_timeout_ms: 5000, write_timeout_ms: 5000, apply_to: 'ALL', is_active: true, note: 'Timeout ngắn để tránh nghẽn khi API Đăng kiểm bị chậm.' },
        { id: '8', timeout_type: 'REPORT_EXPORT', timeout_name: 'Timeout xuất báo cáo PDF/Excel', connect_timeout_ms: 5000, read_timeout_ms: 300000, write_timeout_ms: 300000, apply_to: 'ALL', is_active: true, note: 'Thiết lập thời gian chờ tối đa 5 phút khi kết xuất chứng nhận.' },
        { id: '9', timeout_type: 'API_CALL', timeout_name: 'Timeout API SMS Gateway Viettel', connect_timeout_ms: 2000, read_timeout_ms: 8000, write_timeout_ms: 8000, apply_to: 'ALL', is_active: true, note: 'Khống chế gửi OTP nhanh chóng.' },
        { id: '10', timeout_type: 'DB_QUERY', timeout_name: 'Thời gian chờ truy vấn giao dịch thông thường', connect_timeout_ms: 3000, read_timeout_ms: 15000, write_timeout_ms: 15000, apply_to: 'ALL', is_active: false, note: 'Cấu hình cũ đã tắt.' }
    ],
    UC554: [
        { id: '1', rule_name: 'Địa chỉ mạng văn phòng Tổng cục Hà Nội', ip_type: 'CIDR', cidr_notation: '192.168.1.0/24', apply_to_role: 'ALL', valid_from: '01/01/2026', valid_to: '', is_active: true, description: 'Cho phép toàn bộ dải mạng LAN cơ quan tại Hà Nội kết nối.' },
        { id: '2', rule_name: 'Dải IP kết nối VPN của đội Kỹ thuật/DevOps', ip_type: 'IP_RANGE', ip_from: '10.0.10.1', ip_to: '10.0.10.50', apply_to_role: 'QTHT', valid_from: '01/01/2026', valid_to: '', is_active: true, description: 'Dành riêng cho quản trị viên cấu hình vận hành từ xa qua VPN bảo mật.' },
        { id: '3', rule_name: 'Địa chỉ IP tĩnh Cán bộ Phê duyệt chính', ip_type: 'SINGLE_IP', ip_address: '192.168.1.125', apply_to_role: 'CBPD', valid_from: '10/02/2026', valid_to: '', is_active: true, description: 'IP cố định của máy tính Trưởng phòng Phê duyệt hồ sơ.' },
        { id: '4', rule_name: 'IP máy chủ kiểm thử UAT nội bộ', ip_type: 'SINGLE_IP', ip_address: '10.80.2.14', apply_to_role: 'ALL', valid_from: '01/01/2026', valid_to: '', is_active: true, description: 'Cho phép máy chủ kiểm thử trao đổi tài nguyên.' },
        { id: '5', rule_name: 'Văn phòng Chi nhánh TP. Hồ Chí Minh', ip_type: 'CIDR', cidr_notation: '172.16.20.0/24', apply_to_role: 'ALL', valid_from: '01/03/2026', valid_to: '', is_active: true, description: 'Cấp phép dải IP cơ quan đại diện phía Nam.' },
        { id: '6', rule_name: 'Nhóm hỗ trợ kỹ thuật outsource ngoài giờ', ip_type: 'SINGLE_IP', ip_address: '113.161.45.92', apply_to_role: 'CBNV', valid_from: '15/06/2026', valid_to: '15/09/2026', is_active: true, description: 'IP nhà riêng của cán bộ trực kỹ thuật hệ thống ngoài giờ.' },
        { id: '7', rule_name: 'Máy chủ Trung tâm Dữ liệu dự phòng (DR)', ip_type: 'SINGLE_IP', ip_address: '10.90.1.25', apply_to_role: 'QTHT', valid_from: '01/01/2026', valid_to: '', is_active: true, description: 'IP máy chủ đồng bộ cơ sở dữ liệu khẩn cấp.' },
        { id: '8', rule_name: 'Mạng Wifi khách vãng lai cơ quan', ip_type: 'CIDR', cidr_notation: '192.168.50.0/24', apply_to_role: 'ALL', valid_from: '01/01/2026', valid_to: '', is_active: false, description: 'Đã vô hiệu hóa để chặn truy cập quản trị từ mạng wifi ngoài.' },
        { id: '9', rule_name: 'Cổng kết nối kiểm tra dữ liệu Bộ Tư Pháp', ip_type: 'SINGLE_IP', ip_address: '118.70.124.5', apply_to_role: 'ALL', valid_from: '01/01/2026', valid_to: '', is_active: true, description: 'IP tĩnh máy chủ trung tâm giám sát hạ tầng thông tin Bộ Tư pháp.' },
        { id: '10', rule_name: 'IP tạm thời xử lý sự cố nâng cấp', ip_type: 'IP_RANGE', ip_from: '115.79.80.1', ip_to: '115.79.80.10', apply_to_role: 'QTHT', valid_from: '20/06/2026', valid_to: '22/06/2026', is_active: false, description: 'Đã hết hạn hiệu lực cấu hình khẩn cấp.' }
    ],
    UC555: [
        { id: '1', org_code: 'CUC_DKGD_BTNN', org_name: 'Cục Đăng ký quốc gia giao dịch bảo đảm và Bồi thường nhà nước', org_name_en: 'National Registry of Secured Transactions and State Compensation', org_short_name: 'Cục Đăng ký & BTNN', tax_code: '0101234567', email_primary: 'contact@btp.gov.vn', email_noreply: 'noreply-gdbd@btp.gov.vn', email_support: 'support-gdbd@btp.gov.vn', phone_primary: '024.37335688', phone_hotline: '19001090', fax: '024.37335689', address_full: 'Số 58-60 Trần Phú, Ba Đình, Hà Nội', province_code: 'HN', district_code: 'BD', ward_code: 'QC', website_url: 'https://dkgdbd.gov.vn', facebook_url: 'https://facebook.com/dkgdbd.moj', logo_path: 'logo_cuc_dang_ky.png', favicon_path: 'favicon.ico', is_active: true }
    ],
    UC556: [
        { id: '1', signer_code: 'SGN_001', signer_name: 'Nguyễn Văn Cán Bộ', position: 'Cục Trưởng', department: 'Ban Giám Đốc', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', sign_role: 'AUTHORIZED_SIGNER', sign_position_on_doc: 'BOTTOM_RIGHT', sign_label: 'TM. CỤC TRƯỞNG', signature_image: 'signature_cuc_truong.png', effective_from: '01/01/2025', effective_to: '', apply_to_doc_type: 'CHUNG_THU_DK', is_default: true, is_active: true },
        { id: '2', signer_code: 'SGN_002', signer_name: 'Trần Thị B', position: 'Phó Cục Trưởng', department: 'Ban Giám Đốc', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', sign_role: 'AUTHORIZED_SIGNER', sign_position_on_doc: 'BOTTOM_RIGHT', sign_label: 'KT. CỤC TRƯỞNG\nPHÓ CỤC TRƯỞNG', signature_image: 'signature_pho_cuc_truong.png', effective_from: '01/01/2025', effective_to: '', apply_to_doc_type: 'CHUNG_THU_DK', is_default: false, is_active: true },
        { id: '3', signer_code: 'SGN_003', signer_name: 'Lê Văn C', position: 'Kế toán trưởng', department: 'Phòng Tài chính - Kế hoạch', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', sign_role: 'REVIEWER', sign_position_on_doc: 'BOTTOM_LEFT', sign_label: 'KẾ TOÁN TRƯỞNG', signature_image: 'signature_ke_toan.png', effective_from: '01/01/2025', effective_to: '', apply_to_doc_type: 'HOA_DON', is_default: true, is_active: true },
        { id: '4', signer_code: 'SGN_004', signer_name: 'Phạm Thị D', position: 'Trưởng phòng đăng ký', department: 'Phòng Nghiệp vụ 1', org_unit: 'Trung tâm Đăng ký giao dịch bảo đảm tại Hà Nội', sign_role: 'APPROVER', sign_position_on_doc: 'BOTTOM_RIGHT', sign_label: 'TRƯỞNG PHÒNG ĐĂNG KÝ', signature_image: 'signature_truong_phong.png', effective_from: '01/06/2025', effective_to: '', apply_to_doc_type: 'CHUNG_THU_DK', is_default: false, is_active: true },
        { id: '5', signer_code: 'SGN_005', signer_name: 'Hoàng Văn E', position: 'Chuyên viên kiểm tra', department: 'Phòng Nghiệp vụ 1', org_unit: 'Trung tâm Đăng ký giao dịch bảo đảm tại Hà Nội', sign_role: 'PREPARER', sign_position_on_doc: 'BOTTOM_LEFT', sign_label: 'NGƯỜI LẬP BIỂU', signature_image: 'signature_chuyen_vien.png', effective_from: '01/01/2026', effective_to: '', apply_to_doc_type: 'HOA_DON', is_default: true, is_active: true },
        { id: '6', signer_code: 'SGN_006', signer_name: 'Đỗ Minh F', position: 'Phó phòng nghiệp vụ', department: 'Phòng Nghiệp vụ 2', org_unit: 'Trung tâm Đăng ký giao dịch bảo đảm tại TP. Hồ Chí Minh', sign_role: 'REVIEWER', sign_position_on_doc: 'BOTTOM_RIGHT', sign_label: 'PHÓ TRƯỞNG PHÒNG', signature_image: 'signature_pho_phong.png', effective_from: '01/01/2026', effective_to: '', apply_to_doc_type: 'BIEN_BAN_BAN_GIAO', is_default: true, is_active: true },
        { id: '7', signer_code: 'SGN_007', signer_name: 'Nguyễn Thị G', position: 'Cán bộ Văn thư', department: 'Phòng Hành chính - Tổng hợp', org_unit: 'Trung tâm Đăng ký giao dịch bảo đảm tại Đà Nẵng', sign_role: 'PREPARER', sign_position_on_doc: 'BOTTOM_LEFT', sign_label: 'VĂN THƯ', signature_image: 'signature_van_thu.png', effective_from: '01/01/2026', effective_to: '', apply_to_doc_type: 'BIEN_BAN_BAN_GIAO', is_default: true, is_active: true },
        { id: '8', signer_code: 'SGN_008', signer_name: 'Vũ Văn H', position: 'Giám đốc chi nhánh miền Nam', department: 'Văn phòng đại diện HCM', org_unit: 'Trung tâm Đăng ký giao dịch bảo đảm tại TP. Hồ Chí Minh', sign_role: 'AUTHORIZED_SIGNER', sign_position_on_doc: 'BOTTOM_RIGHT', sign_label: 'TM. VĂN PHÒNG ĐẠI DIỆN', signature_image: 'signature_vp_hcm.png', effective_from: '01/01/2025', effective_to: '', apply_to_doc_type: 'ALL', is_default: false, is_active: true },
        { id: '9', signer_code: 'SGN_009', signer_name: 'Trần Văn I', position: 'Cựu Phó Cục Trưởng', department: 'Ban Giám Đốc', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', sign_role: 'AUTHORIZED_SIGNER', sign_position_on_doc: 'BOTTOM_RIGHT', sign_label: 'KT. CỤC TRƯỞNG', signature_image: 'signature_cu_pho_cuc.png', effective_from: '01/01/2020', effective_to: '31/12/2024', apply_to_doc_type: 'ALL', is_default: false, is_active: false },
        { id: '10', signer_code: 'SGN_010', signer_name: 'Nguyễn Văn K', position: 'Phó Phòng Tài chính', department: 'Phòng Tài chính - Kế hoạch', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', sign_role: 'REVIEWER', sign_position_on_doc: 'BOTTOM_LEFT', sign_label: 'PHÓ PHÒNG TÀI CHÍNH', signature_image: 'signature_pho_ke_toan.png', effective_from: '01/03/2026', effective_to: '', apply_to_doc_type: 'HOA_DON', is_default: false, is_active: true }
    ],
    UC557: [
        { id: '1', seal_code: 'SEL_001', seal_name: 'Con dấu tròn chính Cục ĐKBPBĐ', seal_type: 'ROUND_SEAL', seal_image: 'seal_cuc_dang_ky_chinh.png', seal_position_on_doc: 'OVERLAP_SIGNATURE', size_mm: 40, opacity_percent: 80, apply_to_doc_type: 'CHUNG_THU_DK', effective_from: '01/01/2025', effective_to: '', is_default: true, is_active: true },
        { id: '2', seal_code: 'SEL_002', seal_name: 'Con dấu tròn văn phòng chi nhánh HCM', seal_type: 'ROUND_SEAL', seal_image: 'seal_cuc_dang_ky_hcm.png', seal_position_on_doc: 'OVERLAP_SIGNATURE', size_mm: 40, opacity_percent: 80, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_default: false, is_active: true },
        { id: '3', seal_code: 'SEL_003', seal_name: 'Con dấu chức danh Cục Trưởng', seal_type: 'TITLE_SEAL', seal_image: 'seal_cd_cuc_truong.png', seal_position_on_doc: 'BOTTOM_RIGHT', size_mm: 45, opacity_percent: 90, apply_to_doc_type: 'CHUNG_THU_DK', effective_from: '01/01/2025', effective_to: '', is_default: true, is_active: true },
        { id: '4', seal_code: 'SEL_004', seal_name: 'Con dấu chức danh Phó Cục Trưởng', seal_type: 'TITLE_SEAL', seal_image: 'seal_cd_pho_cuc_truong.png', seal_position_on_doc: 'BOTTOM_RIGHT', size_mm: 45, opacity_percent: 90, apply_to_doc_type: 'CHUNG_THU_DK', effective_from: '01/01/2025', effective_to: '', is_default: false, is_active: true },
        { id: '5', seal_code: 'SEL_005', seal_name: 'Chữ ký số cơ quan Cục ĐKBPBĐ', seal_type: 'DIGITAL_SEAL', seal_image: 'digital_sign_cuc_logo.png', seal_position_on_doc: 'BOTTOM_RIGHT', size_mm: 35, opacity_percent: 100, apply_to_doc_type: 'ALL', effective_from: '01/06/2025', effective_to: '', is_default: true, is_active: true },
        { id: '6', seal_code: 'SEL_006', seal_name: 'Dấu tròn thu phí Hoa đơn VAT', seal_type: 'BRANCH_SEAL', seal_image: 'seal_thu_phi_hoa_don.png', seal_position_on_doc: 'OVERLAP_SIGNATURE', size_mm: 38, opacity_percent: 75, apply_to_doc_type: 'HOA_DON', effective_from: '01/01/2025', effective_to: '', is_default: true, is_active: true },
        { id: '7', seal_code: 'SEL_007', seal_name: 'Con dấu thu tiền mặt văn phòng Hà Nội', seal_type: 'BRANCH_SEAL', seal_image: 'seal_da_thu_tien_hn.png', seal_position_on_doc: 'CUSTOM', offset_x_mm: 20, offset_y_mm: 15, size_mm: 30, opacity_percent: 85, apply_to_doc_type: 'HOA_DON', effective_from: '01/01/2025', effective_to: '', is_default: false, is_active: true },
        { id: '8', seal_code: 'SEL_008', seal_name: 'Dấu chức danh Trưởng phòng nghiệp vụ 1', seal_type: 'TITLE_SEAL', seal_image: 'seal_cd_tr_phong_1.png', seal_position_on_doc: 'BOTTOM_RIGHT', size_mm: 40, opacity_percent: 90, apply_to_doc_type: 'CHUNG_THU_DK', effective_from: '15/06/2025', effective_to: '', is_default: false, is_active: true },
        { id: '9', seal_code: 'SEL_009', seal_name: 'Dấu chức danh Trưởng phòng nghiệp vụ 2', seal_type: 'TITLE_SEAL', seal_image: 'seal_cd_tr_phong_2.png', seal_position_on_doc: 'BOTTOM_RIGHT', size_mm: 40, opacity_percent: 90, apply_to_doc_type: 'BIEN_BAN_BAN_GIAO', effective_from: '15/06/2025', effective_to: '', is_default: false, is_active: true },
        { id: '10', seal_code: 'SEL_010', seal_name: 'Con dấu tròn cũ Cục ĐKBPBĐ (Hết hạn)', seal_type: 'ROUND_SEAL', seal_image: 'seal_cuc_dang_ky_cu.png', seal_position_on_doc: 'OVERLAP_SIGNATURE', size_mm: 40, opacity_percent: 80, apply_to_doc_type: 'ALL', effective_from: '01/01/2015', effective_to: '31/12/2024', is_default: false, is_active: false }
    ],
    UC558: [
        { id: '1', account_code: 'ACC_001', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '110001234567', bank_code: 'VCB', bank_branch: 'Sở giao dịch Vietcombank Hà Nội', bank_province: 'Hà Nội', currency: 'VND', account_type: 'PAYMENT', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', is_default: true, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_active: true, note: 'Tài khoản thu phí đăng ký giao dịch bảo đảm chính.' },
        { id: '2', account_code: 'ACC_002', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '120010203040', bank_code: 'BIDV', bank_branch: 'Chi nhánh Hà Thành', bank_province: 'Hà Nội', currency: 'VND', account_type: 'DEPOSIT', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', is_default: false, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_active: true, note: 'Tài khoản ký quỹ tiền đặt trước của doanh nghiệp.' },
        { id: '3', account_code: 'ACC_003', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '100045678910', bank_code: 'VIETINBANK', bank_branch: 'Chi nhánh Ba Đình', bank_province: 'Hà Nội', currency: 'VND', account_type: 'PAYMENT', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', is_default: false, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_active: true, note: 'Tài khoản thanh toán dự phòng nhận chuyển khoản.' },
        { id: '4', account_code: 'ACC_004', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM - VP MIEN NAM', account_number: '0071001234567', bank_code: 'VCB', bank_branch: 'Chi nhánh Bến Thành', bank_province: 'TP. Hồ Chí Minh', currency: 'VND', account_type: 'PAYMENT', org_unit: 'Trung tâm Đăng ký giao dịch bảo đảm tại TP. Hồ Chí Minh', is_default: false, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_active: true, note: 'Tài khoản thanh toán cho chi nhánh miền Nam.' },
        { id: '5', account_code: 'ACC_005', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '210089898989', bank_code: 'VCB', bank_branch: 'Sở giao dịch Vietcombank Hà Nội', bank_province: 'Hà Nội', currency: 'USD', account_type: 'FOREIGN_CURRENCY', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', swift_code: 'VIETVNVX110', is_default: true, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_active: true, note: 'Tài khoản ngoại tệ phục vụ hợp tác quốc tế.' },
        { id: '6', account_code: 'ACC_006', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '01019999999', bank_code: 'AGRIBANK', bank_branch: 'Chi nhánh Láng Hạ', bank_province: 'Hà Nội', currency: 'VND', account_type: 'PAYMENT', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', is_default: false, apply_to_doc_type: 'THONG_BAO_PHI', effective_from: '10/03/2025', effective_to: '', is_active: true, note: 'Thu nộp phí qua ứng dụng hóa đơn điện tử.' },
        { id: '7', account_code: 'ACC_007', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '1903456789001', bank_code: 'TECHCOMBANK', bank_branch: 'Chi nhánh Đông Đô', bank_province: 'Hà Nội', currency: 'VND', account_type: 'PAYMENT', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', is_default: false, apply_to_doc_type: 'ALL', effective_from: '01/06/2025', effective_to: '', is_active: true, note: 'Tài khoản nhận thanh toán QR Code 247.' },
        { id: '8', account_code: 'ACC_008', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '101056565656', bank_code: 'BIDV', bank_branch: 'Chi nhánh Hà Thành', bank_province: 'Hà Nội', currency: 'USD', account_type: 'FOREIGN_CURRENCY', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', swift_code: 'BIDVVNVX', is_default: false, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_active: true, note: 'Tài khoản ngoại tệ BIDV.' },
        { id: '9', account_code: 'ACC_009', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM', account_number: '110009999999', bank_code: 'VCB', bank_branch: 'Sở giao dịch cũ', bank_province: 'Hà Nội', currency: 'VND', account_type: 'PAYMENT', org_unit: 'Cục Đăng ký quốc gia giao dịch bảo đảm', is_default: false, apply_to_doc_type: 'ALL', effective_from: '01/01/2015', effective_to: '31/12/2024', is_active: false, note: 'Tài khoản VCB đã đóng.' },
        { id: '10', account_code: 'ACC_010', account_holder: 'CUC DANG KY QUOC GIA GIAO DICH BAO DAM - VP MIEN TRUNG', account_number: '0041004321098', bank_code: 'VCB', bank_branch: 'Chi nhánh Đà Nẵng', bank_province: 'Đà Nẵng', currency: 'VND', account_type: 'PAYMENT', org_unit: 'Trung tâm Đăng ký giao dịch bảo đảm tại Đà Nẵng', is_default: false, apply_to_doc_type: 'ALL', effective_from: '01/01/2025', effective_to: '', is_active: true, note: 'Tài khoản phụ trách các tỉnh miền Trung.' }
    ],
    UC559: [
        { id: '1', fee_code: 'FEE_GDBD_REG', fee_name: 'Phí đăng ký biện pháp bảo đảm lần đầu', fee_category: 'PHAN_HE_GDBD', calculation_method: 'FIXED', fee_amount: 80000, currency: 'VND', vat_rate: '0', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '2', fee_code: 'FEE_GDBD_CHG', fee_name: 'Phí đăng ký thay đổi biện pháp bảo đảm', fee_category: 'PHAN_HE_GDBD', calculation_method: 'FIXED', fee_amount: 60000, currency: 'VND', vat_rate: '0', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '3', fee_code: 'FEE_GDBD_DEL', fee_name: 'Phí xóa đăng ký biện pháp bảo đảm', fee_category: 'PHAN_HE_GDBD', calculation_method: 'FIXED', fee_amount: 20000, currency: 'VND', vat_rate: '0', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '4', fee_code: 'FEE_INFO_PROV', fee_name: 'Phí cung cấp thông tin về biện pháp bảo đảm', fee_category: 'PHAN_HE_GDBD', calculation_method: 'FIXED', fee_amount: 30000, currency: 'VND', vat_rate: '0', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '5', fee_code: 'FEE_CERT_COPY', fee_name: 'Phí cấp bản sao chứng nhận đăng ký', fee_category: 'PHAN_HE_GDBD', calculation_method: 'FIXED', fee_amount: 20000, currency: 'VND', vat_rate: '10', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '6', fee_code: 'FEE_BTNN_VAL', fee_name: 'Phí thẩm định hồ sơ bồi thường nhà nước', fee_category: 'PHAN_HE_BTNN', calculation_method: 'FIXED', fee_amount: 0, currency: 'VND', vat_rate: '0', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '7', fee_code: 'FEE_LOAN_VAL_PCT', fee_name: 'Phí thẩm định hồ sơ trị giá lớn theo tỉ lệ', fee_category: 'PHAN_HE_GDBD', calculation_method: 'PERCENTAGE', fee_percentage: 0.05, percentage_base: 'LOAN_AMOUNT', min_fee: 100000, max_fee: 1000000, currency: 'VND', vat_rate: '10', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '8', fee_code: 'FEE_GDBD_TIER', fee_name: 'Biểu phí giao dịch lũy tiến bậc thang', fee_category: 'PHAN_HE_GDBD', calculation_method: 'TIERED', tiered_config: '[{"min":0,"max":100000000,"value":50000},{"min":100000001,"max":500000000,"value":100000},{"min":500000001,"max":999999999999,"value":200000}]', currency: 'VND', vat_rate: '10', effective_from: '01/01/2025', effective_to: '', is_active: true },
        { id: '9', fee_code: 'FEE_GDBD_OLD', fee_name: 'Phí đăng ký lần đầu cũ trước 2025', fee_category: 'PHAN_HE_GDBD', calculation_method: 'FIXED', fee_amount: 100000, currency: 'VND', vat_rate: '0', effective_from: '01/01/2018', effective_to: '31/12/2024', is_active: false },
        { id: '10', fee_code: 'FEE_API_ACCESS', label: 'Phí tích hợp tra cứu hệ thống dành cho Ngân hàng', fee_category: 'DICH_VU_CONG_KHAC', calculation_method: 'FIXED', fee_amount: 10000000, currency: 'VND', vat_rate: '10', effective_from: '01/01/2026', effective_to: '', is_active: true }
    ],
    UC560: [
        { id: '1', check_code: 'VAL_BORROWER_AGE', check_name: 'Kiểm tra độ tuổi người vay thế chấp', check_group: 'NANG_LUC_PHAP_LY', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_BLOCK', condition_expression: 'borrower.age >= 18 && borrower.age <= 80', error_message_vi: 'Người thế chấp tài sản phải nằm trong độ tuổi từ 18 đến 80 tuổi.', error_message_en: 'Borrower age must be between 18 and 80 years old.', check_order: 1, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '2', check_code: 'VAL_TAX_CODE', check_name: 'Kiểm tra độ dài Mã số thuế doanh nghiệp', check_group: 'NANG_LUC_PHAP_LY', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_BLOCK', condition_expression: 'org.taxCode.length == 10 || org.taxCode.length == 13', error_message_vi: 'Mã số thuế doanh nghiệp phải có độ dài đúng 10 số hoặc 13 số.', error_message_en: 'Tax code length must be exactly 10 or 13 digits.', check_order: 2, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '3', check_code: 'VAL_SIGN_PRESENT', check_name: 'Kiểm tra tệp tin chữ ký số đính kèm', check_group: 'HOSODB', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_BLOCK', condition_expression: 'attachments.signature.present == true', error_message_vi: 'Bắt buộc phải có chữ ký số hợp lệ của người yêu cầu đăng ký.', error_message_en: 'Required digital signature of the registration applicant is missing.', check_order: 3, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '4', check_code: 'VAL_ATTACH_SIZE', check_name: 'Kiểm tra kích thước tệp đính kèm tối đa', check_group: 'HOSODB', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_WARN', condition_expression: 'file.size_mb <= 20', error_message_vi: 'Kích thước tệp đính kèm vượt quá 20MB. Hệ thống khuyên dùng tệp dung lượng nhỏ hơn.', error_message_en: 'Attachment size exceeds 20MB limit.', check_order: 4, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '5', check_code: 'VAL_ID_EXPIRED', check_name: 'Kiểm tra CCCD/CMND cá nhân hết hạn', check_group: 'NANG_LUC_PHAP_LY', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_BLOCK', condition_expression: 'person.identityCard.expiryDate > today', error_message_vi: 'Giấy tờ chứng minh nhân thân của chủ thể đã hết hạn sử dụng.', error_message_en: 'Personal identity card has expired.', check_order: 5, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '6', check_code: 'VAL_DEPOSIT_ACC', check_name: 'Kiểm tra số tiền ký quỹ thanh toán phí', check_group: 'PHI_THU_TUC', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_BLOCK', condition_expression: 'account.balance >= transaction.fee', error_message_vi: 'Tài khoản ký quỹ nộp phí của bạn không đủ số dư để thực hiện đăng ký.', error_message_en: 'Insufficient deposit account balance to cover fees.', check_order: 6, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '7', check_code: 'VAL_FEE_PAID', check_name: 'Xác nhận trạng thái đã nộp phí hồ sơ', check_group: 'PHI_THU_TUC', apply_to_process: 'CAP_CHUNG_THU', check_type: 'MANDATORY_BLOCK', condition_expression: 'transaction.paymentStatus == "PAID"', error_message_vi: 'Hồ sơ chưa hoàn thành nộp lệ phí đăng ký. Vui lòng thanh toán trước khi lấy kết quả.', error_message_en: 'Transaction registration fee remains unpaid.', check_order: 7, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '8', check_code: 'VAL_REPRESENT_AUTH', check_name: 'Kiểm tra ủy quyền người đại diện hợp pháp', check_group: 'NANG_LUC_PHAP_LY', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_WARN', condition_expression: 'representative.powerOfAttorney.verified == true', error_message_vi: 'Không tìm thấy thông tin văn bản ủy quyền hợp lệ trong hồ sơ liên thông.', error_message_en: 'Power of attorney details could not be verified in the application.', check_order: 8, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '9', check_code: 'VAL_ATTACH_FORMAT', check_name: 'Kiểm tra định dạng file đính kèm hợp lệ', check_group: 'HOSODB', apply_to_process: 'DANG_KY_BPBD', check_type: 'MANDATORY_BLOCK', condition_expression: 'file.format in ["pdf", "jpg", "png", "doc", "docx"]', error_message_vi: 'Hệ thống chỉ chấp nhận tải lên các tệp tin có định dạng PDF, hình ảnh hoặc tài liệu MS Word.', error_message_en: 'Attachment file format is unsupported.', check_order: 9, effective_from: '01/01/2026', effective_to: '', is_active: true },
        { id: '10', check_code: 'VAL_PHONE_FORMAT', check_name: 'Kiểm tra định dạng số điện thoại liên lạc', check_group: 'NANG_LUC_PHAP_LY', apply_to_process: 'DANG_KY_BPBD', check_type: 'OPTIONAL', condition_expression: 'regex(person.phone, "^[0-9]{10}$")', error_message_vi: 'Số điện thoại liên lạc nên có định dạng 10 chữ số.', error_message_en: 'Phone number should be a 10 digit number format.', check_order: 10, effective_from: '01/01/2026', effective_to: '', is_active: true }
    ],
    UC561: [
        { id: '1', param_key: 'email.smtp.host', param_value: 'smtp.office365.com', param_type: 'STRING', param_group: 'EMAIL', display_name: 'Địa chỉ máy chủ SMTP gửi mail', description: 'Địa chỉ máy chủ Mail Relay phục vụ gửi email thông báo kết quả.', default_value: 'smtp.mail.gov.vn', is_sensitive: false, is_readonly: false, requires_restart: true, is_active: true },
        { id: '2', param_key: 'storage.max.size.mb', param_value: '20', param_type: 'NUMBER', param_group: 'STORAGE', display_name: 'Dung lượng tệp tải lên tối đa', description: 'Giới hạn kích thước tối đa của mỗi tệp đính kèm (PDF/Ảnh) của hồ sơ đăng ký.', default_value: '10', is_sensitive: false, is_readonly: false, requires_restart: false, is_active: true },
        { id: '3', param_key: 'session.timeout.minutes', param_value: '30', param_type: 'NUMBER', param_group: 'SECURITY', display_name: 'Thời gian hết hạn phiên làm việc', description: 'Phiên làm việc tự động Log out sau số phút người dùng không có tương tác nào.', default_value: '30', is_sensitive: false, is_readonly: false, requires_restart: false, is_active: true },
        { id: '4', param_key: 'security.max.login.attempts', param_value: '5', param_type: 'NUMBER', param_group: 'SECURITY', display_name: 'Số lần đăng nhập sai tối đa', description: 'Tài khoản bị khóa tạm thời 15 phút nếu gõ sai mật khẩu liên tiếp vượt quá số này.', default_value: '5', is_sensitive: false, is_readonly: true, requires_restart: false, is_active: true },
        { id: '5', param_key: 'ui.records.per.page', param_value: '10', param_type: 'NUMBER', param_group: 'UI', display_name: 'Số bản ghi hiển thị trên trang', description: 'Số dòng mặc định hiển thị ở các bảng GridView kết quả tra cứu hệ thống.', default_value: '10', is_sensitive: false, is_readonly: false, requires_restart: false, is_active: true },
        { id: '6', param_key: 'integration.napas.url', param_value: 'https://api.napas.com.vn/payment/gate', param_type: 'STRING', param_group: 'INTEGRATION', display_name: 'URL Cổng thanh toán quốc gia Napas', description: 'Địa chỉ cổng API Napas kết nối thu nạp phí.', default_value: 'https://sandbox.napas.com.vn/payment/gate', is_sensitive: false, is_readonly: false, requires_restart: true, is_active: true },
        { id: '7', param_key: 'security.mfa.enabled', param_value: 'true', param_type: 'BOOLEAN', param_group: 'SECURITY', display_name: 'Bật cơ chế xác thực đa nhân tố MFA', description: 'Kích hoạt hoặc vô hiệu hóa toàn bộ cơ chế bảo mật MFA trên hệ thống.', default_value: 'false', is_sensitive: false, is_readonly: false, requires_restart: false, is_active: true },
        { id: '8', param_key: 'notification.sms.active', param_value: 'false', param_type: 'BOOLEAN', param_group: 'NOTIFICATION', display_name: 'Kích hoạt gửi tin nhắn SMS thông báo', description: 'Bật/tắt việc gửi SMS khi hồ sơ được ký duyệt.', default_value: 'false', is_sensitive: false, is_readonly: false, requires_restart: false, is_active: true },
        { id: '9', param_key: 'backup.auto.cron', param_value: '0 0 2 * * ?', param_type: 'STRING', param_group: 'OTHER', display_name: 'Lịch trình sao lưu tự động (Cron)', description: 'Biểu thức Cron thiết lập tiến trình backup DB chạy nền tự động.', default_value: '0 0 2 * * ?', is_sensitive: false, is_readonly: false, requires_restart: true, is_active: true },
        { id: '10', param_key: 'legal.law.version', param_value: 'Nghị định 99/2022/NĐ-CP', param_type: 'STRING', param_group: 'OTHER', display_name: 'Phiên bản căn cứ luật áp dụng', description: 'Văn bản pháp lý in trên tiêu đề chân chứng thư chứng nhận giao dịch.', default_value: '', is_sensitive: false, is_readonly: false, requires_restart: false, is_active: true }
    ],
    UC562: [
        { id: '1', policy_name: 'Bắt buộc MFA đối với Quản trị hệ thống', mfa_methods: 'TOTP, EMAIL_OTP', apply_to_role: 'Quản trị hệ thống (Admin)', enforcement_level: 'MANDATORY', effective_from: '01/01/2026', is_active: true },
        { id: '2', policy_name: 'Áp dụng MFA tùy chọn cho Cán bộ phê duyệt', mfa_methods: 'TOTP, SMS_OTP, EMAIL_OTP', apply_to_role: 'Cán bộ phê duyệt', enforcement_level: 'OPTIONAL', effective_from: '15/02/2026', is_active: true },
        { id: '3', policy_name: 'MFA khi phát hiện thiết bị lạ đăng nhập', mfa_methods: 'EMAIL_OTP', apply_to_role: 'Cán bộ nghiệp vụ', enforcement_level: 'OPTIONAL', effective_from: '01/03/2026', is_active: true },
        { id: '4', policy_name: 'MFA bắt buộc sau khi Khởi tạo lại Mật khẩu', mfa_methods: 'SMS_OTP', apply_to_role: 'Cán bộ nghiệp vụ, Cán bộ phê duyệt', enforcement_level: 'MANDATORY', effective_from: '10/03/2026', is_active: true },
        { id: '5', policy_name: 'MFA khi thực hiện ký số chứng thư', mfa_methods: 'TOTP, PUSH_NOTIFY', apply_to_role: 'Cán bộ phê duyệt, Lãnh đạo đơn vị', enforcement_level: 'MANDATORY', effective_from: '01/05/2026', is_active: true },
        { id: '6', policy_name: 'Chính sách MFA đối với Lãnh đạo đơn vị', mfa_methods: 'TOTP, EMAIL_OTP', apply_to_role: 'Lãnh đạo đơn vị', enforcement_level: 'OPTIONAL', effective_from: '01/01/2026', is_active: true },
        { id: '7', policy_name: 'MFA tùy chọn với CBNV phòng Đăng ký 1', mfa_methods: 'EMAIL_OTP', apply_to_role: 'Cán bộ nghiệp vụ', enforcement_level: 'OPTIONAL', effective_from: '01/06/2026', is_active: true },
        { id: '8', policy_name: 'Bảo mật tăng cường cho tài khoản tài chính', mfa_methods: 'TOTP, SMS_OTP', apply_to_role: 'Kế toán trưởng', enforcement_level: 'MANDATORY', effective_from: '01/01/2026', is_active: true },
        { id: '9', policy_name: 'MFA tạm thời phục vụ đợt đánh giá ATTT', mfa_methods: 'TOTP', apply_to_role: 'ALL', enforcement_level: 'OPTIONAL', effective_from: '15/06/2026', is_active: false },
        { id: '10', policy_name: 'Chính sách MFA cũ cho Cán bộ Văn thư', mfa_methods: 'EMAIL_OTP', apply_to_role: 'Cán bộ nghiệp vụ', enforcement_level: 'DISABLED', effective_from: '01/01/2025', is_active: false }
    ]
};
